import { expect, test } from '@playwright/test';
import { clearIntroDialogue, gameDebugSnapshot, openGame } from './openGame';

test('loads the public demo first screen without page errors', async ({ page }) => {
  test.setTimeout(process.env.PLAYWRIGHT_SKIP_WEBSERVER === 'true' ? 120_000 : 45_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await openGame(page);
  await expect(page.locator('canvas')).toBeVisible();
  await expect(page).toHaveTitle(/Aeon Vale|永恒山谷/);
  await clearIntroDialogue(page);

  const debug = await gameDebugSnapshot(page);
  expect(debug.dialogueBeatId).toBeNull();
  expect(debug.dialogueBackdropVisible).toBe(false);
  expect(debug.todayBriefingVisible).toBe(true);
  expect(debug.panelPreviewVisible).toBe(false);
  expect(debug.locationPreviewVisible).toBe(false);
  expect(debug.paused).toBe(false);
  expect(debug.inventoryVisible).toBe(false);
  expect(debug.cultivationPanelVisible).toBe(false);
  expect(debug.postAscensionMode).toBe('none');
  expect(debug.interactionPanelKind).toBe('none');
  expect(debug.debugSchemaVersion).toBe(2);
  const expectedBuildRevision = process.env.PLAYWRIGHT_EXPECTED_BUILD_REVISION?.trim() || (process.env.PLAYWRIGHT_SKIP_WEBSERVER === 'true' ? null : 'playwright-test');
  if (expectedBuildRevision) expect(debug.buildRevision).toBe(expectedBuildRevision);
  else {
    expect(debug.buildRevision).toEqual(expect.any(String));
    expect(debug.buildRevision).not.toBe('dev');
    expect(debug.buildRevision?.trim()).not.toBe('');
  }
  expect(debug.flowScreen).toBe('world');
  expect(debug.appSurface).toBe('world');
  expect(debug.renderFrameCount).toBeGreaterThan(0);

  expect(debug.day).toBeGreaterThanOrEqual(1);
  expect(debug.season).toMatch(/spring|summer|autumn|winter/);
  expect(debug.seasonDay).toBeGreaterThanOrEqual(1);
  expect(debug.playerHp).toBeGreaterThan(0);
  expect(debug.playerStamina).toBeGreaterThan(0);
  expect(debug.onboardingObjectiveId).toMatch(/^first-/);
  expect(debug.helpText).toEqual(expect.stringContaining('目标'));
  expect(debug.helpText).toEqual(expect.stringContaining('炼丹'));
  expect(debug.helpText).toEqual(expect.stringContaining('引劫'));
  expect(debug.helpText).toEqual(expect.stringContaining('回报'));
  expect(debug.renderedHelpText).toEqual(expect.stringContaining('方向移动'));
  expect(debug.renderedHelpText).toEqual(expect.stringContaining('I 背包'));
  expect(debug.renderedHelpText).toEqual(expect.stringContaining('U 丹炉'));
  expect(debug.renderedHelpText).not.toEqual(expect.stringContaining('\n'));
  expect(debug.renderedHelpText).not.toEqual(expect.stringContaining('function'));
  expect(debug.todayBriefingTitle).toBe('1/4 · 获得灵草');
  expect(debug.todayBriefingBody).toEqual(expect.stringContaining('面对空地翻出第一块灵田'));
  expect(debug.todayBriefingBody).toEqual(expect.stringContaining('炼丹'));
  expect(debug.todayBriefingBody).toEqual(expect.stringContaining('备劫'));
  expect(debug.todayBriefingBody).toEqual(expect.stringContaining('行动：开始翻地'));
  expect(debug.todayBriefingBody).not.toEqual(expect.stringContaining('1/10'));
  expect(debug.todayBriefingAssetId).toBe('logo.full');
  expect(debug.hotbarSlotKind).toBe('till');
  expect(debug.hotbarSeedId).toBeNull();
  expect(debug.selectedLocationId).toBe('farmstead');
  expect(debug.selectedLocationServiceCommand).toBe('show-farm-work');
  expect(debug.starterMosslingSeedCount).toBe(6);
  expect(debug.starterDewrootSeedCount).toBe(3);
  expect(debug.starterMosslingHerbCount).toBe(3);
  expect(debug.starterDewrootHerbCount).toBe(2);
  expect(debug.starterSpiritStoneCount).toBe(2);
  expect(debug.shippingBinItemCount).toBe(0);
  const idleFrameCount = debug.renderFrameCount;
  await page.waitForTimeout(160);
  expect((await gameDebugSnapshot(page)).renderFrameCount).toBe(idleFrameCount);
  expect(errors).toEqual([]);
});
