import type { SimContext } from '@sim/world/context';
import type { GameState } from '@sim/world/state';
import { emit } from '@sim/world/state';
import { MILLI, Season } from '@sim/world/types';

export interface TeaShedRumor {
  id: string;
  title: string;
  lines: readonly string[];
}

/** 旧茶棚歇脚事件分支：特定节气日会偶遇一位茶客留下奇闻与点拨，额外增益意志。 */
export interface TeaShedTale {
  id: string;
  title: string;
  line: string;
  willpowerBonus: number;
}

export interface VisitTeaShedResult {
  ok: boolean;
  reason?: string;
  rumor: TeaShedRumor;
  season: Season;
  hpGain: number;
  poisonRelief: number;
  willpowerGain: number;
  staminaCost: number;
  streak: number;
  streakBonus: number;
  tale: TeaShedTale | null;
}

/** 旧茶棚歇脚的体力消耗随季而变：身体的安坐节律与四时相应。 */
const TEA_SHED_STAMINA_COST_BY_SEASON: Record<Season, number> = {
  spring: 18, // 生发，标准
  summer: 20, // 暑热难安
  autumn: 15, // 秋高气爽，最易安坐
  winter: 16 // 冬藏深息
};

/** 各季额外清闲收益（春为基准，零加成，保持既有节奏；其余三季各得一抹季节性格调）。 */
const TEA_SHED_SEASONAL_HP_MILLI: Record<Season, number> = { spring: 0, summer: 0, autumn: 0, winter: 4 };
const TEA_SHED_SEASONAL_POISON_CAP: Record<Season, number> = { spring: 0, summer: 1, autumn: 0, winter: 0 };
const TEA_SHED_SEASONAL_WILLPOWER: Record<Season, number> = { spring: 0, summer: 0, autumn: 60, winter: 0 };

/** 茶客奇闻池：每季第 5 的倍数日（5/10/15/20/25）会偶遇一位茶客留下点拨。 */
export const TEA_SHED_TALES: readonly TeaShedTale[] = [
  { id: 'tale.wandering-sword', title: '游侠赠言', line: '一位游侠临行前留下一句：守住一亩三分地，比追着天道跑更难。', willpowerBonus: 40 },
  { id: 'tale.old-farmer', title: '老农的土方', line: '邻座老农说，越是留世的人，越要把每一茬收成当最后一茬来种。', willpowerBonus: 40 },
  { id: 'tale.mortal-lantern', title: '凡人灯火', line: '茶棚外凡人灯火又亮了一盏，你忽然觉得，能护住这点光已是修行。', willpowerBonus: 50 },
  { id: 'tale.hermit-advice', title: '隐士点拨', line: '角落里一位隐士搁下茶碗：体修不走天，走的是地；地把根扎稳了，天雷也劈不动。', willpowerBonus: 50 },
  { id: 'tale.merchant-rumor', title: '行商传闻', line: '行商说起外乡阵坊的新式护田阵，你默默记下几笔，回头好改进自家田里的布法。', willpowerBonus: 40 },
  { id: 'tale.pill-reject', title: '拒丹客', line: '邻座散商说自己早年拒过一枚捷径丹：靠丹催出来的境界，雷劫来了最先散。', willpowerBonus: 40 },
  { id: 'tale.fellow-farmer', title: '同田旧识', line: '一位旧年同在凡间种地的熟人认出你，笑着说：到底还是把那把锄头攥到了飞升边上。', willpowerBonus: 50 },
  { id: 'tale.silent-watch', title: '无言守望', line: '棚角老者整夜不语，只盯着远处灵田的方向——你忽然懂了，守田守到极致，便是无言的守望。', willpowerBonus: 40 },
  { id: 'tale.greenhouse-keeper', title: '棚主旧事', line: '老棚主讲起早年在暖棚里熬过整个寒冬的事：守得住一棚苗，就守得住一整年的指望。', willpowerBonus: 50 },
  { id: 'tale.rain-blessing', title: '喜雨兆', line: '茶客说昨夜那场雨下得正是时候，是老天给留得住田的人的一点回应。', willpowerBonus: 40 },
  { id: 'tale.beast-pact', title: '巡守盟约', line: '一位老巡守带着他的巡守兽来歇脚。「它替你守田，你替它留一世安稳——人兽之间这条路，走到底比丹药还顶用。」', willpowerBonus: 50 },
  { id: 'tale.void-echo', title: '空苔回响', line: '茶客讲起山里一种灰白、不吸灵气的苔，谁也种不活。你心里一动——空亦有空之用，那味绝灵苔，兴许正该换个种法。', willpowerBonus: 50 },
  { id: 'tale.formation-dust', title: '残阵落灰', line: '角落一位老人抖开一卷落满灰的残阵图。「阵这东西，吃透了进肉里比画在地上还稳——可惜我老了，走不动这条路了。」', willpowerBonus: 40 },
  { id: 'tale.commission-debt', title: '委托旧账', line: '一位行商翻出泛黄的旧委托账册。「守得住承诺的人，山谷才肯把更深的道交给它——一单一单做扎实，比贪多丢得少。」', willpowerBonus: 40 },
  { id: 'tale.spirit-vein-hum', title: '灵脉低鸣', line: '茶棚地板隐隐传来低鸣，与脚下灵脉同频。「老茶客说，灵脉顺了，田里灵机才肯往上走；不顺，再好的苗也憋在土里。」', willpowerBonus: 40 },
  { id: 'tale.elder-furnace', title: '老丹炉', line: '一位老炼丹客讲起他用了半辈子的丹炉。「火候最难控的不是温度，是火性——同一种火，对不同的料是恩赐还是灾，全看你接不接得住。」', willpowerBonus: 50 },
  { id: 'tale.wine-seller', title: '酒客品酿', line: '酒客抿了口自酿的灵药酒，咂嘴道：「陈酿这事急不来，留世的人最不缺的就是日子——越陈越能把药性养圆。」', willpowerBonus: 40 },
  { id: 'tale.array-warden-visit', title: '阵守过客', line: '一位过路的阵守讲起他在别处布的护田阵。「阵守不是守阵，是守人——阵纹在你心里，你往哪站，阵的势就往哪倾。」', willpowerBonus: 50 },
  { id: 'tale.dawn-plow', title: '晨犁', line: '天还没亮，一位老农已套好犁。「灵田不等人——趁着晨气最清翻地，这一茬的根就比旁人扎得深一寸。」', willpowerBonus: 40 },
  { id: 'tale.seed-keeper', title: '守种人', line: '茶客掏出一只贴身藏的种子袋。「好种比好田更难得——留世久了你就懂，守住一袋种，就守住了来年的指望。」', willpowerBonus: 50 },
  { id: 'tale.frost-watch', title: '寒夜守望', line: '雪夜，一位巡守裹着蓑衣进棚烤火。「冷到位时最怕松神——苗根冻裂就在一两个时辰里，熬过去，开春就比谁都早。」', willpowerBonus: 40 },
  { id: 'tale.tribute-memory', title: '贡品旧忆', line: '老人讲起早年间镇上的灵石大祭。「贡的不是石头，是心意——山谷认你这份稳，才肯在妖潮来时替你挡一挡。」', willpowerBonus: 40 },
  { id: 'tale.lost-recipe', title: '失传丹方', line: '一位散修叹息着摊开半页焦黑残卷。「最可惜的不是炸炉，是把一条丹方带进了坟——你既走体修的路，残卷可得收好了。」', willpowerBonus: 50 },
  { id: 'tale.twilight-weed', title: '暮采', line: '茶客讲起傍晚采药的讲究。「日头落下那刻药性最敛——留世的人不赶时辰，专挑这时候采，事半功倍。」', willpowerBonus: 40 },
  { id: 'tale.market-haggle', title: '集市还价', line: '行商讲起在集市与散修周旋的门道。「凡骨议价弱，但认货的人不欺货——你把灵草养到够真够纯，价自然往你这边靠。」', willpowerBonus: 40 },
  { id: 'tale.stone-ward', title: '灵石压阵', line: '老人摆出几颗温润的灵石。「镇守之夜，几颗灵石压住阵脚，比一柄快刀更顶用——稳，从来是体修的根。」', willpowerBonus: 40 },
  { id: 'tale.dewroot-tea', title: '露根清茶', line: '茶棚常备一壶露根草熬的清茶。「最普通的草，熬到位也是最养人的茶——体修的路，本就是把凡物用到极致。」', willpowerBonus: 40 },
  { id: 'tale.broken-talisman', title: '残宝余温', line: '茶客递来一片还泛着微温的法宝碎件。「法宝碎了不全是废——体修不靠法宝吃饭，这些残件熔一熔，正好补阵。」', willpowerBonus: 40 },
  { id: 'tale.archive-dust', title: '藏经旧页', line: '一位老学究抖落卷上浮灰。「藏经阁缺的不是孤本，是有人肯把游历所得归档进去——你留下的每一页，都是后来者的路。」', willpowerBonus: 50 },
  { id: 'tale.beast-tide-memory', title: '妖潮旧劫', line: '老人讲起多年前那场妖潮。「妖潮来时不看你境界多高，看你的田守没守住——守住了，山谷就记得你这个人。」', willpowerBonus: 40 },
  { id: 'tale.seasonal-turn', title: '四时轮转', line: '茶客望着窗外换季的天色。「留世久了就懂，四时不是劫，是节奏——跟着它走，比逆着它熬轻松十倍。」', willpowerBonus: 40 },
  { id: 'tale.heaven-debt', title: '天债', line: '一位散修苦笑着摇头。「主动引劫的代价是天债——欠得越多，天越盯着你；体修的路，就是把这份债慢慢还成资粮。」', willpowerBonus: 40 },
  { id: 'tale.dao-attention', title: '天道注视', line: '茶客压低声音讲起被天道注视的感觉。「不是雷劈你，是那道目光——熬得住注视的人，才熬得住后来的雷。」', willpowerBonus: 50 },
  { id: 'tale.lifespan-sand', title: '寿沙', line: '老人摊开掌心一把细沙。「寿元就是这把沙，留世的人不图多，图的是每一粒都落在该落的地方。」', willpowerBonus: 40 },
  { id: 'tale.iron-will', title: '铁心', line: '一位断臂老修士讲起当年的执念。「体修走到最后靠的不是根骨，是这颗铁了的心——心不散，雷就劈不散你。」', willpowerBonus: 50 },
  { id: 'tale.pill-poison', title: '丹毒旧痛', line: '一位散修掀开衣襟露出青黑的脉。「丹毒比刀伤更阴——它不痛，却一点一点蚀你的根；留世的人，排毒比进补更要紧。」', willpowerBonus: 40 },
  { id: 'tale.tribulation-omen', title: '天劫前兆', line: '茶客讲起引劫前那几日的异感。「天要劈你之前，连田里的草都会先低头——读懂这些前兆，你才好选哪个夜迎上去。」', willpowerBonus: 50 },
  { id: 'tale.farm-layout', title: '田畴布法', line: '一位老农用茶水在桌上画出田垄。「种田不是乱撒——哪株引雷、哪株挡风、哪株养命，布好了，天劫之夜你的田就是一座阵。」', willpowerBonus: 40 },
  { id: 'tale.stable-days', title: '稳住的日子', line: '茶客讲起何谓「稳住」。「不是不遇事，是遇事还能回得了棚、歇得下脚——连着稳住几日，留世的日子才算真正落地。」', willpowerBonus: 40 },
  { id: 'tale.endurance-train', title: '淬体旧法', line: '一位老体修讲起淬体的笨法子。「没什么巧——就是把痛一口一口咽下去，咽到身子自己学会把痛变成劲；这法子慢，但不伤根。」', willpowerBonus: 40 },
  { id: 'tale.quiet-harmony', title: '闲和', line: '茶客讲起留世后最难得的心境。「不是无所事事，是闲里也守得住和——和气养住了，田里棚里自然都顺。」', willpowerBonus: 40 },
  { id: 'tale.wandering-poet', title: '云游诗客', line: '一位诗客在棚柱上题了半句留世的诗。「飞升是别人的事，种田是我们的诗——题完他笑着走了，说下次来要喝你的药茶。」', willpowerBonus: 50 },
  { id: 'tale.mist-fern-dew', title: '雾蕨露', line: '茶客讲起山里雾蕨叶尖凝的露。「那露最养神识——可惜雾蕨难寻，能种出一片的人，留世便多了一味稳神的底药。」', willpowerBonus: 40 },
  { id: 'tale.beast-core-glow', title: '内丹温光', line: '茶客掌心一颗内丹泛着暖光。「妖兽的内丹不是杀伐之物——熬到位，它是最暖的淬体火种；体修不弃杀，也不止于杀。」', willpowerBonus: 40 },
  { id: 'tale.sealed-herb-fragrance', title: '封藏药香', line: '一股陈香从茶客的药匣里溢出。「封藏灵草养的是岁月——封得越久，药性越往内敛，留世的人最懂这份慢工。」', willpowerBonus: 50 },
  { id: 'tale.array-core-hum', title: '阵核低吟', line: '茶客掏出一枚阵核，在桌上嗡嗡作响。「阵核是阵的心——心稳了，整座阵才不散；体修布阵，先养这颗心。」', willpowerBonus: 40 },
  { id: 'tale.compost-brew', title: '灵壤酝酿', line: '茶客讲起自家堆沤灵壤肥的法门。「灵壤肥急不得——一层草一层土，沤到火候，撒下去的苗就比别人壮一截。」', willpowerBonus: 40 },
  { id: 'tale.recipe-fragment-tale', title: '残卷补遗', line: '茶客摊开半页残卷，缺角处用炭笔补全。「体修的丹方散在天下各处——你每补一页，就替后来人少走一段弯路。」', willpowerBonus: 40 },
  { id: 'tale.poultice-balm', title: '药膏旧方', line: '一位老药婆讲起外敷药膏的讲究。「内服养根，外敷救急——体修挨的打多，药膏这块手艺比丹方更救命。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-storm', title: '暖棚过雷', line: '茶客讲起那年雷季，暖棚替半村苗挡了灾。「棚不只是育苗，是替你留底的保险——雷来得再凶，棚里那几株就是来年的根。」', willpowerBonus: 50 },
  { id: 'tale.courier-stipend', title: '跑腿酬谢', line: '茶客笑说起递送巡守兽的好处。「那兽子替你跑腿，邻里心里记着——以灵石酬谢，是山谷认你这份勤勉的人情。」', willpowerBonus: 40 },
  { id: 'tale.old-well', title: '古井', line: '茶棚后一口古井，井水清冽。「这井比棚还老——体修不挑风水，但认得一口稳井的价值：旱时它不竭，就是底气。」', willpowerBonus: 40 },
  { id: 'tale.bonded-plow', title: '老犁', line: '墙角立着一把磨得发亮的旧犁。「犁是体修第一件法器——它不发光，却替你把凡骨一寸寸种进了这片土。」', willpowerBonus: 50 },
  { id: 'tale.frostmarrow-cold', title: '寒髓冷', line: '茶客讲起寒潭莲那股透骨的凉。「寒髓莲镇阴最绝——阴邪夜犯时，一茎寒髓便能把邪气压回暗处。」', willpowerBonus: 40 },
  { id: 'tale.balmleaf-warmth', title: '和合暖', line: '茶客讲起和合叶化浊的本事。「瘴气、丹毒，和合叶都能和缓地化开——它不猛，却最体贴体修的身子。」', willpowerBonus: 40 },
  { id: 'tale.suncap-dawn', title: '朝阳暖', line: '茶客讲起朝阳菇迎着日头撑伞的模样。「朝阳菇认日头——种在向阳处，它就替你把晨气攒成养苗的暖。」', willpowerBonus: 40 },
  { id: 'tale.stonegrain-porridge', title: '粟石粥', line: '茶棚常熬一锅粟石草粥。「粟石草最养凡骨——一碗热粥下肚，干一天的活也不慌。」', willpowerBonus: 40 },
  { id: 'tale.mossling-carpet', title: '青苔毯', line: '茶棚墙根一片凡间青苔。「青苔最贱也最韧——凡骨种田，先从这耐活的苔学起，慢慢就有了根。」', willpowerBonus: 40 },
  { id: 'tale.dewroot-soup', title: '露根汤', line: '茶客讲起露根草覆根御寒的用处。「霜夜覆一把露根在苗根上，就冻不坏——它护的不是自己，是整片田的来年。」', willpowerBonus: 40 },
  { id: 'tale.metalpine-ember', title: '雷击木', line: '茶客讲起那棵被雷劈过却还活的雷击木。「雷击木是体修的图腾——劈不死它的雷，也劈不死走这条路的人。」', willpowerBonus: 50 },
  { id: 'tale.emberheart-fire', title: '赤炎心', line: '茶客讲起赤炎草那团温而不烈的火性。「赤炎草养的是真火——不烧人，只暖脉；体修用它温骨，比烈丹更稳。」', willpowerBonus: 40 },
  { id: 'tale.thunderreed-channel', title: '引雷芦', line: '茶客讲起引雷芦那根空心的茎。「引雷芦替你把雷引到该去的地方——体修布阵诱雷，少不了它当那根导火索。」', willpowerBonus: 40 },
  { id: 'tale.ironwill-thorn', title: '铁心刺', line: '茶客讲起铁心刺那身扎手的硬刺。「铁心刺护田最硬——妖兽撞上来，先被它的刺扎退；它替你的阵顶在第一线。」', willpowerBonus: 50 },
  { id: 'tale.sunmoss-ash', title: '烬阳灰', line: '茶客讲起烬阳苔燃尽后留下的暖灰。「烬阳苔烧自己暖别人——体修淬体到要紧处，一捧烬阳灰就是续命的火种。」', willpowerBonus: 40 },
  { id: 'tale.mistfern-smoke', title: '雾蕨烟', line: '茶客讲起雾蕨熏香净场的旧俗。「雾蕨一燃，浊气就散——祭礼、镇邪、净田，山谷里少不了这一缕清烟。」', willpowerBonus: 40 },
  { id: 'tale.stay-choice', title: '留与去', line: '茶客讲起当年自己面对飞升抉择的那夜。「飞升是走，留世是守——没有高下，只有你愿不愿意把这片田认作归宿。」', willpowerBonus: 50 },
  { id: 'tale.purple-bolt', title: '紫雷劫', line: '老人讲起紫雷劫的可怕。「紫雷不是劈身，是劈心——熬过它的人，要么飞升，要么像我们这样，留下。」', willpowerBonus: 50 },
  { id: 'tale.body-foundation', title: '体魄根', line: '茶客讲起体魄这座根基。「体魄不是修出来的，是一锄一犁种出来的——根扎在土里，雷才拔不动你。」', willpowerBonus: 40 },
  { id: 'tale.storage-ring', title: '储物戒', line: '茶客摩挲着指上一只旧储物戒。「这戒子陪我半辈子——留世的人，家当不在多，在随时拿得出来。」', willpowerBonus: 40 },
  { id: 'tale.violet-bolt', title: '紫电', line: '茶客讲起紫电划破夜空的瞬间。「紫电比紫雷更先到——它不伤身，只慑魂；扛得住这道光的人，才配迎后面的雷。」', willpowerBonus: 50 },
  { id: 'tale.farmstead-quiet', title: '农庄夜', line: '茶客讲起夜里独守农庄的那份静。「不是孤单，是踏实——棚里兽子打着呼，田里苗在长，你在，这一切就在。」', willpowerBonus: 40 },
  { id: 'tale.tool-rust', title: '锈工具', line: '茶客摸着一把磨得光亮的锄。「工具不怕旧，怕生锈——天天用，它就天天亮；体修的身子也是这个理。」', willpowerBonus: 40 },
  { id: 'tale.beast-pup', title: '幼兽', line: '茶客讲起当年捡回那只幼兽的事。「它那时还不会护田，却肯跟着我守夜——巡守兽的忠，是从它还小时养起的。」', willpowerBonus: 40 },
  { id: 'tale.lightning-rod-tale', title: '引雷阵', line: '茶客讲起引雷阵那根直指天空的阵杆。「引雷阵是把双刃剑——引来的雷既能淬熟金属性灵草，也能烧田；布它的人，得算得清这份险。」', willpowerBonus: 40 },
  { id: 'tale.insulation-array', title: '绝缘阵', line: '茶客讲起绝缘阵那圈隔开雷势的残纹。「绝缘阵不争雷心，只把雷势导到阵缘——核心几块田稳住了，雷季就有了底气。」', willpowerBonus: 40 },
  { id: 'tale.festival-memory', title: '节庆旧事', line: '茶客讲起山谷节庆的热闹。「节庆不只是热闹——那是山谷认你、邻里认你的日子，留世的人最该过好这几个节。」', willpowerBonus: 40 },
  { id: 'tale.hermit-hut', title: '隐士庐', line: '茶客讲起山深处那位隐士的草庐。「隐士不见客，却肯留半卷给有缘人——你若路过，记得替他扫扫门前那片落叶。」', willpowerBonus: 50 },
  { id: 'tale.herb-gatherer-tale', title: '采药女', line: '茶客讲起采药女分辨药性的好眼力。「她认草比认人还准——山谷里谁家灵草出了岔，都爱去找她把一把脉。」', willpowerBonus: 40 },
  { id: 'tale.array-smith-tale', title: '阵匠老陆', line: '茶客讲起阵匠老陆那双布满老茧的手。「他布的阵不花哨，却最稳——体修的阵，要的就是这份笨功夫。」', willpowerBonus: 40 },
  { id: 'tale.wandering-cultivator-tale', title: '游方散修', line: '茶客讲起那位游方散修的好行情。「他走南闯北，什么稀奇货都收——山谷里要换外头的物件，找他最是方便。」', willpowerBonus: 40 },
  { id: 'tale.child-question', title: '稚子问', line: '茶棚里一个孩童仰头问老人：「种田也能成仙吗？」老人笑着揉他脑袋：「成不成仙不打紧，把田种好，你就是这片山谷的神。」', willpowerBonus: 50 },
  { id: 'tale.greenhouse-climate-tale', title: '棚候', line: '茶客讲起暖棚里那套调候的窍门。「棚候稳了，离季也能育苗——这份稳，是留世的人用一夜一夜守出来的。」', willpowerBonus: 40 },
  { id: 'tale.river-spirit', title: '溪灵', line: '茶客讲起山溪里若隐若现的灵。「溪灵不显形，却肯替干净的人引一路水——体修不拜神，但敬这份无声的帮衬。」', willpowerBonus: 50 },
  { id: 'tale.elder-memory', title: '老者忆', line: '一位老者讲起年轻时也尝试过引劫。「我没能扛过那道雷——你既走这条路，就替我们这些没走完的人，把它走完。」', willpowerBonus: 50 },
  { id: 'tale.traveler-map', title: '旅人图', line: '茶客摊开一张画满记号的旧地图。「体修不云游，可也该知道山谷外长什么样——这份图，算我替你开的窗。」', willpowerBonus: 40 },
  { id: 'tale.seasonal-equinox', title: '春分', line: '茶客讲起春分那日田里的生机。「春分一过，地气就活了——留世的人最看重这个节，它替你定下整年的根。」', willpowerBonus: 40 },
  { id: 'tale.beast-trace-tale', title: '妖痕', line: '茶客讲起田埂边那道新鲜妖兽抓痕。「妖兽来探田不是要吃，是探你守不守——你守住了，它下回就不来。」', willpowerBonus: 40 },
  { id: 'tale.wine-vintage', title: '陈酿', line: '茶客讲起藏了十年的那坛药酒。「药酒越陈越养——急的人喝不出味，留世的人才能等到它最好的那年。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-perfume', title: '棚香', line: '茶客讲起推门进暖棚那股扑面的香。「棚香是苗在呼吸——闻得到这股香，说明你把棚候养对了。」', willpowerBonus: 40 },
  { id: 'tale.dew-collector', title: '采露', line: '茶客讲起清晨采灵草叶上露的法子。「那层露最养神——留世的人不嫌麻烦，一滴一滴攒，也能聚成味良药。」', willpowerBonus: 40 },
  { id: 'tale.rock-breaker', title: '碎石', line: '茶客讲起翻地时撞上的硬石。「碎石别丢——垫在阵脚，就是现成的阵基；体修眼里没有废物。」', willpowerBonus: 40 },
  { id: 'tale.ash-fertilizer', title: '灰肥', line: '茶客讲起用烬阳苔灰拌土施肥的门道。「一捧暖灰拌进土，苗的根就暖了——这是体修才懂的种田法。」', willpowerBonus: 40 },
  { id: 'tale.frostmarrow-lamp', title: '寒髓灯', line: '茶客讲起寒髓莲瓣做成夜灯的旧俗。「寒髓灯不亮，却清幽——阴邪不近，是夜守田的人最爱的灯。」', willpowerBonus: 50 },
  { id: 'tale.herbal-tea-master', title: '茶娘', line: '茶棚的茶娘熬得一手好药茶。「她说茶是药的头一程——把茶熬好的人，离炼丹也就近了一步。」', willpowerBonus: 40 },
  { id: 'tale.bonded-sickle', title: '旧镰', line: '茶客讲起他用了三十年的旧镰。「镰刃薄了，却更顺手——工具和人一样，磨合久了，才合拍。」', willpowerBonus: 40 },
  { id: 'tale.pail-water', title: '灵水', line: '茶客讲起灵水桶里那口井水。「水灵不灵，看井——好井浇出的苗，根都比旁人的壮。」', willpowerBonus: 40 },
  { id: 'tale.seed-catalog', title: '种册', line: '茶客翻出一本记满种名的旧册。「留种的人都有这么一本——哪粒种哪年留的，记清楚，来年才不乱。」', willpowerBonus: 40 },
  { id: 'tale.festival-lantern', title: '节灯', line: '茶客讲起节庆夜满棚的灯笼。「节灯亮起来，山谷就认你是自家人——这份光，比境界更暖人。」', willpowerBonus: 40 },
  { id: 'tale.beast-core-lamp', title: '丹灯', line: '茶客讲起用内丹做芯的长明灯。「丹灯不灭，妖兽不近——体修的田头，都该挂这么一盏。」', willpowerBonus: 40 },
  { id: 'tale.mist-fern-wick', title: '雾蕨芯', line: '茶客讲起用雾蕨做灯芯的讲究。「雾蕨芯燃出的烟能驱瘴——一灯两用，是留世人精打细算的智慧。」', willpowerBonus: 40 },
  { id: 'tale.storage-attic', title: '阁楼', line: '茶客讲起自家阁楼堆着的旧物。「阁楼堆的不是破烂，是底——哪天田里出了事，阁楼上总能翻出救急的件。」', willpowerBonus: 40 },
  { id: 'tale.dawn-rooster', title: '晨鸡', line: '茶棚外的晨鸡准时打鸣。「连鸡都认得留世的节律——它一叫，你就该起，这片山谷的日子从不等人。」', willpowerBonus: 40 },
  { id: 'tale.evening-smoke', title: '晚炊', line: '茶客讲起各户晚炊升起的烟。「看炊烟就知道谁家还在过日子——留世的人，炊烟一日不断，就是一日没认输。」', willpowerBonus: 40 },
  { id: 'tale.compost-pit', title: '沤肥坑', line: '茶客讲起他家那口老沤肥坑。「坑要年年翻——沤透的灵壤肥，撒下去的苗就比别人早醒一旬。」', willpowerBonus: 40 },
  { id: 'tale.array-compass', title: '阵盘', line: '茶客掏出一面刻满纹路的旧阵盘。「阵盘是布阵的眼——拿着它站田头，哪该引、哪该挡，一眼就清。」', willpowerBonus: 40 },
  { id: 'tale.beast-whistle', title: '驯哨', line: '茶客讲起驯巡守兽的那只小哨。「哨声比喊声管用——兽认哨，慢慢就认你；驯兽这事，急不得。」', willpowerBonus: 40 },
  { id: 'tale.spirit-stone-coin', title: '灵石钱', line: '茶客讲起灵石在山谷里当钱使的门道。「灵石硬通货——谁手里有灵石，谁说话就硬气几分，凡骨也一样。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-thermometer', title: '棚温计', line: '茶客讲起挂在棚里的那只温计。「温计不是摆设——差一两度，苗就差一截；留世的人，眼睛得盯着它。」', willpowerBonus: 40 },
  { id: 'tale.broken-talisman-ring', title: '残宝戒', line: '茶客指上套着一只用残宝改的戒。「残件也能派用场——熔一熔、改一改，就是只护身的戒，体修不挑。」', willpowerBonus: 40 },
  { id: 'tale.dawn-dew', title: '晨露', line: '茶客讲起天将亮未亮时那层薄露。「晨露最养神——留世的人早起一刻，就能多接一份天地刚醒时的清气。」', willpowerBonus: 40 },
  { id: 'tale.evening-bell', title: '晚钟', line: '茶客讲起山寺传来的晚钟。「钟声一响，田里棚里都该收一收神——留世的夜，是从这声钟开始的。」', willpowerBonus: 40 },
  { id: 'tale.mountain-shadow', title: '山影', line: '茶客讲起日落时山影压过田的瞬间。「山影压下来，灵机就敛——体修的人懂得借这份阴，把白日的燥火压回去。」', willpowerBonus: 40 },
  { id: 'tale.valley-echo', title: '谷回', line: '茶客讲起对着山谷喊一声能听见回音。「回音是山谷在应你——留世久了，连山都肯跟你一问一答。」', willpowerBonus: 40 },
  { id: 'tale.stone-tablet', title: '石碑', line: '茶客讲起田头那块磨平字迹的旧石碑。「碑文早看不清了，可它立着，这片田就有了主——体修也是，立住个念头，路就不散。」', willpowerBonus: 50 },
  { id: 'tale.rooftile-rain', title: '瓦上雨', line: '茶客讲起雨打瓦的声音。「瓦上雨最催眠——留世的夜里听一会，比一炉丹更养神。」', willpowerBonus: 40 },
  { id: 'tale.courtyard-sweep', title: '扫院', line: '茶客讲起每日清晨扫院的习惯。「院子扫干净，心也跟着清——体修的修行，一半就在这一扫帚一扫帚里。」', willpowerBonus: 40 },
  { id: 'tale.old-bridge-tale', title: '旧桥忆', line: '茶客讲起山谷口那座老木桥。「桥修了又修，修桥的人都老去了——你既留下，就替他们把这座桥守好。」', willpowerBonus: 40 },
  { id: 'tale.harvest-moon', title: '秋月', line: '茶客讲起秋夜那轮又大又圆的月。「秋月下收的灵草药性最足——留世的人趁月色抢收，比白日多一分灵。」', willpowerBonus: 40 },
  { id: 'tale.first-snow', title: '初雪', line: '茶客讲起入冬第一场雪。「初雪盖棚，是给暖棚的考验——撑过去，这一冬的苗就有了底气。」', willpowerBonus: 40 },
  { id: 'tale.spring-thaw', title: '春融', line: '茶客讲起冻土融化的那一刻。「春融一开，就该翻地了——体修的年，从这一锄下去才算开始。」', willpowerBonus: 40 },
  { id: 'tale.summer-storm-tale', title: '夏暴雨', line: '茶客讲起夏日那场浇透田的暴雨。「暴雨是把双刃——浇透了是福，冲了苗就是祸；留世的人，雨前得把沟理清。」', willpowerBonus: 40 },
  { id: 'tale.autumn-frost', title: '秋霜', line: '茶客讲起秋晨田埂上那层白霜。「秋霜一来，该收的就得收完——再拖一夜，灵草的药性就散了一半。」', willpowerBonus: 40 },
  { id: 'tale.winter-solstice', title: '冬至', line: '茶客讲起冬至夜最长的那一夜。「冬至守夜，守的是来年的根——留世的人在这夜把棚里的苗都看一遍，心里才踏实。」', willpowerBonus: 50 },
  { id: 'tale.new-year', title: '岁除', line: '茶客讲起岁除夜山谷的烟火。「岁除的烟火不是给人看的，是替旧年谢土——体修不拜天，可这份谢，得有。」', willpowerBonus: 40 },
  { id: 'tale.lantern-festival', title: '灯节', line: '茶客讲起灯节满棚挂上的小灯。「灯节的灯替你照一照来年的路——亮一夜，也算替旧友故人引个方向。」', willpowerBonus: 40 },
  { id: 'tale.pain-as-teacher', title: '痛为师', line: '茶客讲起淬体时那份痛。「痛不是敌人，是师父——它教你哪里还弱，哪里还要练；体修的人，得会听痛说话。」', willpowerBonus: 40 },
  { id: 'tale.slow-is-fast', title: '慢即快', line: '茶客讲起留世后才悟的道理。「急的人走了一辈子还在原地——慢的人一步一个印，反而走得最远；体修尤其如此。」', willpowerBonus: 40 },
  { id: 'tale.root-before-branch', title: '先根后枝', line: '茶客讲起种树先养根的道理。「根不深，枝再繁也是虚——体修不追花哨的境界，只把根往土里扎。」', willpowerBonus: 40 },
  { id: 'tale.empty-mind', title: '空心', line: '茶客讲起引劫前要空的心。「心里装太多，雷就劈得中——空了心，雷反而找不到落点；这是体修的保命诀。」', willpowerBonus: 50 },
  { id: 'tale.water-cuts-stone', title: '水穿石', line: '茶客指着棚外滴水穿石的檐。「水最软，却穿得透石——体修的人，凭的就是这股不急不歇的软劲。」', willpowerBonus: 40 },
  { id: 'tale.bend-not-break', title: '曲则全', line: '茶客讲起风中竹子弯而不折的样子。「硬抗会断，弯一下就过去——体修遇雷，也得懂这份曲；曲不是怂，是全。」', willpowerBonus: 50 },
  { id: 'tale.return-to-dust', title: '归尘', line: '茶客讲起身死后归尘的道理。「体修不求长生不老，只求这一把骨能种出几株好苗——归尘，是体修最体面的收场。」', willpowerBonus: 40 },
  { id: 'tale.one-stroke', title: '一笔力', line: '茶客讲起一锄下去要用整身力的窍门。「不是手在锄，是身在锄——一笔力用对了，干一天田也比旁人养体。」', willpowerBonus: 40 },
  { id: 'tale.furnace-clay', title: '炉泥', line: '茶客讲起丹炉内壁那层老炉泥。「炉泥养久了，火性就稳——体修的丹炉，炉泥比炉身还金贵。」', willpowerBonus: 40 },
  { id: 'tale.pill-mold', title: '丹模', line: '茶客讲起那只传了三代的丹模。「好丹模出好丹——模上的纹路，是前辈一笔一笔刻进去的心血。」', willpowerBonus: 40 },
  { id: 'tale.array-brush', title: '阵笔', line: '茶客讲起画阵纹的那支秃笔。「阵笔不用新——秃一点的笔，画出的纹反而更浑厚，像体修的性子。」', willpowerBonus: 40 },
  { id: 'tale.water-channel', title: '水渠', line: '茶客讲起田边那条石砌水渠。「水渠通不通，决定苗渴不渴——留世的人，第一件事就是把渠理顺。」', willpowerBonus: 40 },
  { id: 'tale.stone-wall', title: '石墙', line: '茶客讲起田四周的矮石墙。「石墙挡的不是人，是风和兽——体修的田，先有一圈墙，才有安稳。」', willpowerBonus: 40 },
  { id: 'tale.wood-fence', title: '木栅', line: '茶客讲起栅栏上缠的荆棘。「栅栏加道刺，妖兽就不爱来——这是凡间最朴素的护田法，比阵还早。」', willpowerBonus: 40 },
  { id: 'tale.seedbed-tray', title: '苗盘', line: '茶客讲起育苗用的旧木盘。「苗盘一格一格，分得清——好苗是从小被分清楚养大的，混着养就废。」', willpowerBonus: 40 },
  { id: 'tale.storage-shelf', title: '物架', line: '茶客讲起仓里那排分门别类的物架。「物架分得清，急用时就不慌——体修的家，乱不得。」', willpowerBonus: 40 },
  { id: 'tale.firefly-night', title: '萤夜', line: '茶客讲起夏夜棚外点点萤火。「萤火是灵机散在虫身上——留世的夜，有它陪着，就不显孤单。」', willpowerBonus: 40 },
  { id: 'tale.owl-watch', title: '枭守', line: '茶客讲起夜里蹲在棚顶的猫头鹰。「它替你守夜，眼比灯还亮——体修的田，连鸟都肯来帮一把。」', willpowerBonus: 40 },
  { id: 'tale.bee-pollinate', title: '蜂媒', line: '茶客讲起灵蜂替灵草传粉的好处。「灵蜂一过，灵草结籽就多——这份忙，是山谷白给的帮衬。」', willpowerBonus: 40 },
  { id: 'tale.spider-web', title: '蛛网', line: '茶客讲起棚角蛛网上的露珠。「蛛网不碍事，还能捕蚊虫——体修眼里万物有用，留着它就是。」', willpowerBonus: 40 },
  { id: 'tale.koi-pond', title: '鲤池', line: '茶客讲起院里那池养了多年的灵鲤。「灵鲤活得久，比人还沉得住——看着它游，心就静了。」', willpowerBonus: 40 },
  { id: 'tale.wild-rabbit', title: '野兔', line: '茶客讲起田边偷苗的野兔。「兔子偷苗不气人，倒提醒你栅栏该补了——体修的人，连贼都当成师。」', willpowerBonus: 40 },
  { id: 'tale.eagle-shadow', title: '鹰影', line: '茶客讲起天上盘旋的鹰影。「鹰盯的是兔，可也替你惊着妖兽——留世的田，天上地下都有帮手。」', willpowerBonus: 40 },
  { id: 'tale.cricket-song', title: '蛐鸣', line: '茶客讲起秋夜蛐蛐的叫声。「蛐鸣是秋的钟——它一唱，留世的人就知道该收该藏了。」', willpowerBonus: 40 },
  { id: 'tale.wind-chime', title: '风铃', line: '茶客讲起挂在檐下的旧风铃。「风铃一响，就知道风向变了——留世的人靠它料天气，比卜算还准。」', willpowerBonus: 40 },
  { id: 'tale.clay-pot', title: '陶罐', line: '茶客讲起腌灵草用的那只老陶罐。「陶罐透气，腌出的灵草不坏——体修的家什，朴素的反而最顶用。」', willpowerBonus: 40 },
  { id: 'tale.bamboo-flute', title: '竹笛', line: '茶客讲起夜里吹一曲竹笛的习惯。「笛声能稳兽、能静神——体修不奏雅乐，可这一曲，是给自己的歇。」', willpowerBonus: 40 },
  { id: 'tale.ink-stone', title: '砚台', line: '茶客讲起记田事用的那方旧砚。「好砚磨出的墨不滞——留世的人把每天的田事记下，来年就有谱可循。」', willpowerBonus: 40 },
  { id: 'tale.stone-bench', title: '石凳', line: '茶客讲起田头那只磨得发亮的石凳。「干累了坐一坐，比躺还解乏——体修的歇，不在多，在这一坐的工夫。」', willpowerBonus: 40 },
  { id: 'tale.old-scroll', title: '旧卷', line: '茶客讲起柜里那卷没读完的旧书。「旧书读一半，留着慢慢嚼——体修的道理，急读读不出味，得拿日子配。」', willpowerBonus: 40 },
  { id: 'tale.broken-idol', title: '残像', line: '茶客讲起棚角那尊缺了头的小像。「它不是神，是先人的念——留着它，是提醒自己这条路上不止你一个人走过。」', willpowerBonus: 50 },
  { id: 'tale.dust-mirror', title: '尘镜', line: '茶客讲起墙上一面蒙尘的旧镜。「镜子不照脸，照心——擦一擦看一看，知道自己还是不是当初那个人。」', willpowerBonus: 40 },
  { id: 'tale.neighbor-borrow', title: '邻借', line: '茶客讲起邻家来借灵石的事。「借是情分，还是情分——山谷里谁都有难时，今天借出去，明天就借得回来。」', willpowerBonus: 40 },
  { id: 'tale.child-laughter', title: '童笑', line: '茶客讲起棚外孩童追逐的笑。「童笑最养神——留世的人听见这声，就知道这片山谷还有明天。」', willpowerBonus: 40 },
  { id: 'tale.traveler-rest', title: '旅人歇', line: '茶客讲起一位过路旅人在棚里歇脚。「他讲的外头的事，你听个新鲜——可歇完他还是走，你还得回田里。」', willpowerBonus: 40 },
  { id: 'tale.widow-tea', title: '孤孀茶', line: '茶客讲起独守亡夫灵田的老妇。「她不修仙，只守田——这份守，比飞升更让山谷记得她。」', willpowerBonus: 50 },
  { id: 'tale.youth-ambition', title: '少年志', line: '茶客讲起棚里那位想飞升的少年。「他眼里有火，你眼里有田——两条路都不错，只是体修知道，哪条都得熬。」', willpowerBonus: 40 },
  { id: 'tale.old-couple', title: '老两口', line: '茶客讲起田那头并肩干活的老两口。「他们没修过一天仙，可那份白头——是连飞升者也羡慕的圆满。」', willpowerBonus: 50 },
  { id: 'tale.elder-gossip', title: '老叟闲谈', line: '茶客讲起几位老人聚一块聊旧事。「旧事越聊越远，可聊着聊着，山谷的来处就清楚了——体修也该知道自己从哪来。」', willpowerBonus: 40 },
  { id: 'tale.couple-quarrel', title: '夫妻拌嘴', line: '茶客讲起邻家两口子为琐事拌嘴。「拌嘴不是怨，是日子——能拌到老的，都是体修该学的修法。」', willpowerBonus: 40 },
  { id: 'tale.noon-shade', title: '午阴', line: '茶客讲起正午躲阴的片刻。「午阴里歇一气，下午才有力——体修的人，懂得什么时候该歇手。」', willpowerBonus: 40 },
  { id: 'tale.sunset-glow', title: '夕照', line: '茶客讲起夕照染红灵田的那一刻。「夕照下的灵草，药性都带着一份暖——留世的人，连收成都挑时辰。」', willpowerBonus: 40 },
  { id: 'tale.starlit-field', title: '星夜田', line: '茶客讲起星夜守田的清净。「星光照着灵田，比灯还静——体修的人，最爱这一份没人打扰的夜。」', willpowerBonus: 40 },
  { id: 'tale.dawn-mist-field', title: '晨雾田', line: '茶客讲起晨雾里若隐若现的灵田。「雾里的田，灵机最足——趁雾翻地，那一份潮气就养进了根里。」', willpowerBonus: 40 },
  { id: 'tale.dusk-cookfire', title: '暮炊火', line: '茶客讲起各家升起的炊火。「炊火一升，一日就收了尾——留世的日子，就在这一灶火里踏实下来。」', willpowerBonus: 40 },
  { id: 'tale.midnight-watch', title: '子夜守', line: '茶客讲起子夜最静时的守。「子夜是阴极，也是阳气初生——体修守这一刻，是为接住那一点初生的阳。」', willpowerBonus: 50 },
  { id: 'tale.dawn-cock-crow', title: '晓鸡啼', line: '茶客讲起第一声鸡啼前的静。「鸡啼前最黑，也最近天明——体修的谷底，总挨着破晓。」', willpowerBonus: 40 },
  { id: 'tale.twilight-haze', title: '暮霭', line: '茶客讲起山间聚起的暮霭。「暮霭一笼，山谷就闭了眼——体修的人，跟着它一起歇，比硬撑强。」', willpowerBonus: 40 },
  { id: 'tale.wind-test', title: '风试', line: '茶客讲起山谷的风。「风是灵田的筛子——根浅的苗被风一试就倒，根深的反而越扎越牢。」', willpowerBonus: 40 },
  { id: 'tale.rain-test', title: '雨试', line: '茶客讲起一场透雨。「雨试的是沟——沟顺的田越下越润，沟堵的田一场就涝；体修靠雨验田。」', willpowerBonus: 40 },
  { id: 'tale.fire-test', title: '火试', line: '茶客讲起丹炉的火。「火试的是人——同一炉火，手稳的出好丹，手抖的炸炉；火不挑人，人得配得上火。」', willpowerBonus: 40 },
  { id: 'tale.earth-test', title: '土试', line: '茶客讲起翻地时土的手感。「土试的是心——急的人翻得浅，沉的人翻得透；体修的深浅，土最清楚。」', willpowerBonus: 40 },
  { id: 'tale.cold-snap', title: '骤寒', line: '茶客讲起入秋那场骤寒。「骤寒最伤苗——留世的人听到风声就提前覆棚，这份警觉是挨冻挨出来的。」', willpowerBonus: 40 },
  { id: 'tale.heat-wave', title: '酷暑', line: '茶客讲起盛夏最难熬的酷暑。「酷暑里棚温一过线，苗就蔫——留世的人，三伏天整夜守着排气窗。」', willpowerBonus: 40 },
  { id: 'tale.drought-tale', title: '旱', line: '茶客讲起那年大旱。「旱时灵井见底，才知一口好井的贵——体修不挑风水，但旱过的人最懂井的价值。」', willpowerBonus: 40 },
  { id: 'tale.flood-tale', title: '涝', line: '茶客讲起连阴雨成涝的那年。「涝比旱更阴——水排不出去，根就烂；留世的人，田边那条沟是命。」', willpowerBonus: 40 },
  { id: 'tale.sharpen-blade', title: '磨刃', line: '茶客讲起磨锄刃的工夫。「刃磨得利，干活省一半力——体修的人，舍得花半日磨刃，是最大的省力。」', willpowerBonus: 40 },
  { id: 'tale.mend-net', title: '补网', line: '茶客讲起补那张破了的灵网。「网破一处就补一处——留着不补，破得更快；体修的家什，勤补比换新省。」', willpowerBonus: 40 },
  { id: 'tale.weave-basket', title: '编筐', line: '茶客讲起用灵藤编筐的手艺。「自己编的筐最称手——体修不挑贵物，能用自己手做的，就不假外求。」', willpowerBonus: 40 },
  { id: 'tale.carve-wood', title: '刻木', line: '茶客讲起夜里刻木消遣的习惯。「刻木能静手、能静心——体修的手要稳，这份闲工夫是最好的练。」', willpowerBonus: 40 },
  { id: 'tale.tan-hide', title: '鞣革', line: '茶客讲起鞣妖兽皮做护具的门道。「兽皮鞣透了，比铁甲还贴身——体修的护具，自己鞣的最懂自己的身。」', willpowerBonus: 40 },
  { id: 'tale.spin-thread', title: '纺线', line: '茶客讲起纺灵草纤维成线的慢活。「纺线急不得——一抽一抽，线才匀；体修的耐性，就养在这慢活里。」', willpowerBonus: 40 },
  { id: 'tale.knit-cloth', title: '织布', line: '茶客讲起织布的节奏。「织布像种田——一梭一梭，急不出幅；体修的人，最懂这份一梭一梭的稳。」', willpowerBonus: 40 },
  { id: 'tale.fire-pottery', title: '烧陶', line: '茶客讲起自家窑里烧出的陶。「自己烧的陶，知道火候——体修用的每一件，都该是自己懂的东西。」', willpowerBonus: 40 },
  { id: 'tale.first-harvest', title: '初收', line: '茶客讲起头一茬灵草收割时的心情。「那一把收成，比金子还沉——体修的人，从初收那刻起，才算真正信了自己能种。」', willpowerBonus: 40 },
  { id: 'tale.first-planting', title: '初播', line: '茶客讲起头一次播下灵草种。「手抖着撒的种，怕它不活——可它偏偏活了，那刻你才懂，山谷是认你的。」', willpowerBonus: 40 },
  { id: 'tale.first-tribulation', title: '初劫', line: '茶客讲起头一回引劫的夜。「那一夜最长——扛过来后，天亮的颜色都不一样了；体修的人，初劫是分水岭。」', willpowerBonus: 50 },
  { id: 'tale.first-beast', title: '初兽', line: '茶客讲起头一只驯下的巡守兽。「它刚来时不认你，一夜一夜守下来，它把头靠过来了——那份初信，比灵石重。」', willpowerBonus: 50 },
  { id: 'tale.first-pill', title: '初丹', line: '茶客讲起头一枚炼成的丹。「炸了好几炉，才成一枚——那枚丹没舍得吃，留着，是体修的底气。」', willpowerBonus: 40 },
  { id: 'tale.first-array', title: '初阵', line: '茶客讲起头一回布成的护田阵。「阵纹画歪了好几遍，亮起来那刻——你才知道自己也能控一片势。」', willpowerBonus: 40 },
  { id: 'tale.first-friend', title: '初交', line: '茶客讲起头一个在山谷交下的朋友。「不图什么，就是处得来——体修的路长，有一个初交，路就不冷清。」', willpowerBonus: 40 },
  { id: 'tale.first-loss', title: '初失', line: '茶客讲起头一回失去的灵田或兽。「那份痛记得就好——体修的人，从初失那刻起，才真正学会了守。」', willpowerBonus: 40 },
  { id: 'tale.bent-old-tree', title: '弯腰树', line: '茶客讲起山口那棵弯了半辈子的老树。「它直不起来，可活最久——体修也该懂，弯不一定是输，是让过风。」', willpowerBonus: 40 },
  { id: 'tale.cracked-bowl', title: '裂碗', line: '茶客讲起棚里那只补过锔的裂碗。「碗裂了补一补，照样喝茶——体修的人，破了的也能补回来，不必弃。」', willpowerBonus: 40 },
  { id: 'tale.dull-blade-master', title: '钝刃师', line: '茶客讲起那位用钝刀刻出绝阵的老匠。「刀钝，手却精——体修不靠利器，靠这份磨钝了也不松手的劲。」', willpowerBonus: 50 },
  { id: 'tale.blind-toucher', title: '盲摸', line: '茶客讲起那位盲着眼摸灵草辨药性的老人。「眼瞎了，手更灵——体修到了绝处，总有别的感官替你顶上。」', willpowerBonus: 40 },
  { id: 'tale.mute-teacher', title: '哑师', line: '茶客讲起那位说不了话却教出半个山谷的哑师。「他从不讲道理，只做——体修的人，做的比说的，教得更深。」', willpowerBonus: 50 },
  { id: 'tale.deaf-listener', title: '聋听', line: '茶客讲起那位听不见却最懂人心的聋翁。「他听不见话，却看得见神——体修的人，眼睛比耳朵更该练。」', willpowerBonus: 40 },
  { id: 'tale.one-legged-heron', title: '独脚鹭', line: '茶客讲起田边那只独脚站着的鹭。「少一脚也站得稳——体修的人，缺什么都能找补，关键是站稳。」', willpowerBonus: 40 },
  { id: 'tale.slow-turtle-parable', title: '钝龟喻', line: '茶客讲起山谷溪里那只慢吞吞的老龟。「它一辈子没快过，可活得比谁都久——体修的人，认了慢，就赢了长。」', willpowerBonus: 40 },
  { id: 'tale.omen-crow', title: '鸦兆', line: '茶客讲起田边那只聒噪的乌鸦。「鸦叫不全是凶——有时它是在提醒你哪块田出了岔；体修的人，连凶兆都听出吉意。」', willpowerBonus: 40 },
  { id: 'tale.dream-sign', title: '梦兆', line: '茶客讲起前夜那个怪梦。「梦里的田比现实绿——他说这是山谷在给你看盼头；体修的人，梦也是养料。」', willpowerBonus: 40 },
  { id: 'tale.fortune-stick', title: '求签', line: '茶客讲起棚里那只旧签筒。「签上的话半通半不通——体修不信命，可抽一签静一静心，倒也无妨。」', willpowerBonus: 40 },
  { id: 'tale.ancestor-shrine', title: '先人龛', line: '茶客讲起田头那座小小的先人龛。「不烧香，只鞠一躬——体修的根，一半在自己身上，一半在这些先人留下的土里。」', willpowerBonus: 50 },
  { id: 'tale.karmic-debt', title: '因果', line: '茶客讲起山谷里那份看得见的因果。「你种什么，山谷还什么——体修的人最信因果，因为田从不骗人。」', willpowerBonus: 40 },
  { id: 'tale.spirit-pact', title: '灵约', line: '茶客讲起与一只灵兽默立的那份约。「没立字据，只是彼此信——这份灵约，比阵纹还牢。」', willpowerBonus: 50 },
  { id: 'tale.reincarnation-whisper', title: '轮回低语', line: '茶客讲起偶尔耳边的低语。「像是谁在前世喊你——体修不求来世，可这份低语提醒你，路是接得上的。」', willpowerBonus: 40 },
  { id: 'tale.divination-sticks', title: '卜竹', line: '茶客讲起掷卜竹的老法子。「卜竹是给自己一个交代——体修的人，卜完还是得靠手，可这份交代能让心定。」', willpowerBonus: 40 },
  { id: 'tale.callused-hand', title: '茧手', line: '茶客摊开满是老茧的手。「体修的境界不在丹田，在这双手的茧上——茧厚一分，路就稳一分。」', willpowerBonus: 40 },
  { id: 'tale.sweat-soil', title: '汗浸土', line: '茶客讲起汗水滴进土里的感觉。「汗是体修给田的供——你流多少汗，田就还你多少收成，从不差分毫。」', willpowerBonus: 40 },
  { id: 'tale.sunburned-back', title: '晒背', line: '茶客讲起夏田里被晒脱皮的后背。「背晒脱了一层，体魄就厚了一层——体修的人，阳光也是师父。」', willpowerBonus: 40 },
  { id: 'tale.sore-muscle', title: '酸骨', line: '茶客讲起干完一天田浑身酸的那种痛快。「酸是长——不酸说明没用力；体修的人，把酸当成生长的信号。」', willpowerBonus: 40 },
  { id: 'tale.dirty-nail', title: '泥甲', line: '茶客讲起指甲缝里洗不掉的泥。「体修的指甲该有泥——干干净净的手，种不出好灵草。」', willpowerBonus: 40 },
  { id: 'tale.tired-sleep', title: '累眠', line: '茶客讲起累极倒头就睡的那种沉。「那种沉，是金山也换不来——体修的人，累到这份上，才睡得真。」', willpowerBonus: 40 },
  { id: 'tale.hungry-meal', title: '饥餐', line: '茶客讲起饿透后那一碗粗茶淡饭的香。「饿透的饭最香——体修的人，懂得留着饿意，才尝得出日子的味。」', willpowerBonus: 40 },
  { id: 'tale.cold-drink', title: '寒饮', line: '茶客讲起夏田回来那一碗井水镇凉的茶。「一碗凉茶下肚，暑气全消——这是体修的福，飞升也换不来这一刻的舒坦。」', willpowerBonus: 40 },
  { id: 'tale.fading-memory', title: '淡忆', line: '茶客讲起记得越来越清、却又越来越远的旧友。「他走了多年，可留世的田里还有他帮过的一锄——体修的人，记人不在坟前，在田里。」', willpowerBonus: 50 },
  { id: 'tale.rotten-fence', title: '朽栅', line: '茶客讲起年年要换的朽栅栏。「栅栏会朽，可换栅栏的手不会老——体修的人，朽了就换，不怨天。」', willpowerBonus: 40 },
  { id: 'tale.crumbled-wall', title: '塌墙', line: '茶客讲起塌了一段的田墙。「墙塌了别急砌——先看为什么塌，是水、是根、还是兽；体修的人，连塌墙都当教材。」', willpowerBonus: 40 },
  { id: 'tale.dried-up-well', title: '涸井', line: '茶客讲起那年冬天见底的灵井。「井涸了一季，来年又满——体修的人信，涸到底的东西，往往还会再满回来。」', willpowerBonus: 40 },
  { id: 'tale.overgrown-field', title: '荒田', line: '茶客讲起山谷口那片荒了的灵田。「荒了不一定是废——让它歇几年，再种时反而更肥；体修也懂歇。」', willpowerBonus: 40 },
  { id: 'tale.faded-sign', title: '褪字', line: '茶客讲起棚柱上褪了色的旧字。「字褪了，意思还在——体修的传承也是，字会淡，做不会。」', willpowerBonus: 40 },
  { id: 'tale.broken-bench', title: '断凳', line: '茶客讲起棚外那条断了的旧石凳。「断凳没人坐，可都舍不得搬——它立过的地方，就有故事；体修的人重旧物。」', willpowerBonus: 40 },
  { id: 'tale.torn-curtain', title: '破帘', line: '茶客讲起棚里那幅补了又补的旧帘。「帘破了挡不住风，可挡得住眼——体修的家，破帘也是体面。」', willpowerBonus: 40 },
  { id: 'tale.smell-rain', title: '雨味', line: '茶客讲起雨将来时空气里那股土腥味。「闻到这味就知道该收棚了——体修的鼻子，比卜算还灵。」', willpowerBonus: 40 },
  { id: 'tale.smell-earth', title: '土香', line: '茶客讲起翻地时新土的那股香。「土香是地在呼吸——体修闻着这味翻地，比施肥还养田。」', willpowerBonus: 40 },
  { id: 'tale.smell-herb', title: '药香', line: '茶客讲起棚里飘出的灵草药香。「药香是灵草在长大——闻着香，就知道这一棚养对了。」', willpowerBonus: 40 },
  { id: 'tale.sound-thunder', title: '雷声', line: '茶客讲起远处滚来的雷声。「雷声是天的脚步——体修的人听雷，不慌，只盘算自己的阵布好了没。」', willpowerBonus: 40 },
  { id: 'tale.sound-water', title: '水声', line: '茶客讲起渠水哗哗流过田的声音。「水声是田在喝水——留世的人最爱听这个，比乐还悦耳。」', willpowerBonus: 40 },
  { id: 'tale.sight-firefly', title: '萤光', line: '茶客讲起夏夜灵萤聚成的光河。「萤光聚多了，能照田——体修的人不点灯，借这一河光守夜。」', willpowerBonus: 40 },
  { id: 'tale.touch-bark', title: '树皮', line: '茶客讲起老树皮粗糙的手感。「树皮糙，可它护着的是里面嫩的层——体修的皮也该糙，护住里面的根。」', willpowerBonus: 40 },
  { id: 'tale.taste-tea', title: '茶味', line: '茶客讲起一壶老药茶回甘的味。「茶味在回甘——体修的日子也是，苦过之后那一口甘，才是真味。」', willpowerBonus: 40 },
  { id: 'tale.barter-fair', title: '以物易物', line: '茶客讲起早年没灵石时以物易物的日子。「一袋种换两块肉，凭的是信——体修的经济，信比灵石还硬。」', willpowerBonus: 40 },
  { id: 'tale.savings-jar', title: '储坛', line: '茶客讲起埋在棚柱下的那坛存灵石。「存一点是一点——体修的人，不图暴富，图的是手里有底。」', willpowerBonus: 40 },
  { id: 'tale.thrift', title: '节俭', line: '茶客讲起一件工具用了二十年的节俭。「节俭不是穷，是惜——体修的人，惜物惜福，路才走得长。」', willpowerBonus: 40 },
  { id: 'tale.generosity', title: '大方', line: '茶客讲起那年把存粮分给邻居的事。「大方不是傻——分出去的，山谷早晚连本带利还回来。」', willpowerBonus: 50 },
  { id: 'tale.fair-price', title: '公道价', line: '茶客讲起做买卖只取公道价的坚持。「价压太低，伤的是自家的名声——体修做生意，要的是长久。」', willpowerBonus: 40 },
  { id: 'tale.debt-repay', title: '还债', line: '茶客讲起欠的债一定要还的执念。「债是因果——欠了不还，雷劫来时先劈你这份不守信；体修的人，债比命重。」', willpowerBonus: 40 },
  { id: 'tale.debt-forgiven', title: '免债', line: '茶客讲起免了一位老邻的旧债。「他还不起了，就免了——体修的人，该狠时狠，该松时也得松。」', willpowerBonus: 50 },
  { id: 'tale.loan-spirit-stone', title: '借灵石', line: '茶客讲起借灵石给急用的邻人。「借出去就别想着马上要回——体修的人，借是情分，急不得还。」', willpowerBonus: 40 },
  { id: 'tale.teach-child', title: '授徒', line: '茶客讲起教邻家孩童认灵草的日子。「教的不是草，是这条路的接续——体修的人，留世久了，总得有人接着走。」', willpowerBonus: 40 },
  { id: 'tale.elder-lesson', title: '老者训', line: '茶客讲起被老人训了一顿的旧事。「那顿训救了我一命——体修的人，听得进训，才活得久。」', willpowerBonus: 40 },
  { id: 'tale.apprentice-mistake', title: '徒弟错', line: '茶客讲起徒弟炸了炉时自己的反应。「没骂，只让他看清楚哪步错——体修的传承，错也是教。」', willpowerBonus: 40 },
  { id: 'tale.master-patience', title: '师耐心', line: '茶客讲起自己师父当年那份耐心。「他教了我三遍同一招——现在我才懂，那份耐心是体修最贵的传承。」', willpowerBonus: 50 },
  { id: 'tale.lineage-stories', title: '传承', line: '茶客讲起山谷里一代代传下来的故事。「故事比丹方更值钱——它教你怎么活，不只教你怎么炼。」', willpowerBonus: 50 },
  { id: 'tale.unwritten-rule', title: '不成文', line: '茶客讲起山谷里那些不成文的规矩。「没刻在碑上，可人人都守——体修的人，守的不成文，比成文的还多。」', willpowerBonus: 40 },
  { id: 'tale.observed-silence', title: '默观', line: '茶客讲起师父只看不说的教法。「他不说，让我自己悟——体修的悟，都是默观里熬出来的。」', willpowerBonus: 40 },
  { id: 'tale.corrected-gently', title: '轻纠', line: '茶客讲起被师父轻轻一句纠过来的方向。「他没说我错，只问我想去哪——体修的师，引而不压。」', willpowerBonus: 40 },
  { id: 'tale.solo-meal', title: '独食', line: '茶客讲起一个人吃饭的那份静。「独食不凄凉——能安安静静吃下一碗饭，是体修的人才有的福。」', willpowerBonus: 40 },
  { id: 'tale.solo-night', title: '独夜', line: '茶客讲起独自守棚的那些夜。「独夜最考验心——熬得住的人，心就稳了；体修的定力，独夜里养。」', willpowerBonus: 40 },
  { id: 'tale.reflection-pond', title: '映心', line: '茶客讲起院里那池能映心的水。「水静才映得清——体修的人，心静了，自己才看得见自己。」', willpowerBonus: 50 },
  { id: 'tale.quiet-regret', title: '静悔', line: '茶客讲起夜里想起的旧错。「悔是好事——它说明你比那时懂事了；体修的人，不避悔，只不再犯。」', willpowerBonus: 40 },
  { id: 'tale.grateful-heart', title: '感恩', line: '茶客讲起对这片山谷的感恩。「山谷给了你田、给了你日子——体修的人，心里存着感恩，路才走得暖。」', willpowerBonus: 50 },
  { id: 'tale.forgive-self', title: '自恕', line: '茶客讲起终于原谅自己那年犯的错。「不恕自己，路就走不动——体修的人，得学会放过自己一马。」', willpowerBonus: 40 },
  { id: 'tale.accept-limit', title: '认限', line: '茶客讲起承认自己有做不到的事。「认限不是认输——是知道哪些田自己种得了，哪些种不了；体修的人，认限才稳。」', willpowerBonus: 40 },
  { id: 'tale.solo-harvest', title: '独收', line: '茶客讲起一个人收完整片田的那种满足。「没人看，也满足——体修的收获，不为给人看，只为自己心里实。」', willpowerBonus: 40 },
  { id: 'tale.drunk-beast', title: '醉兽', line: '茶客笑讲一只偷喝了药酒的巡守兽，醉得转圈。「它第二天宿醉没精神护田——体修的人，连兽的酒都得藏好。」', willpowerBonus: 40 },
  { id: 'tale.lazy-apprentice', title: '懒徒', line: '茶客笑讲那个总爱偷懒的小徒弟。「他偷懒的法子比干活的法子还多——可教着教着，也成了材；体修的人，得有这份耐心。」', willpowerBonus: 40 },
  { id: 'tale.mixed-up-seed', title: '错种', line: '茶客笑讲自己当年把寒潭莲种进了旱地的糗事。「苗没活，倒长出一地野草——体修的人，错也是经验，记着别再犯。」', willpowerBonus: 40 },
  { id: 'tale.runaway-pig', title: '逃猪', line: '茶客笑讲邻家猪拱进灵田偷吃的那夜。「追了一宿猪，比引一次劫还累——体修的田，连猪都得防。」', willpowerBonus: 40 },
  { id: 'tale.burnt-meal', title: '糊饭', line: '茶客笑讲自己炼丹走神把饭烧糊的事。「丹没炸，饭炸了——体修的人，一心不能二用，这是血的教训。」', willpowerBonus: 40 },
  { id: 'tale.snoring-elder', title: '鼾叟', line: '茶客笑讲棚角那位打呼震天的老翁。「他的呼噜比雷还响——体修的人笑说，听他打呼，等于预习雷劫。」', willpowerBonus: 40 },
  { id: 'tale.forgot-tool', title: '忘具', line: '茶客笑讲到田头才发现锄忘家里的尴尬。「来回一趟，半天没了——体修的人，出门前默念一遍家什，省的是时间。」', willpowerBonus: 40 },
  { id: 'tale.rained-out', title: '淋透', line: '茶客笑讲自己被骤雨淋成落汤鸡的窘样。「淋透一次，以后就知道看云了——体修的人，吃亏是福。」', willpowerBonus: 40 },
  { id: 'tale.ancient-farmer', title: '古农', line: '茶客讲起山谷第一位种灵草的古农。「他不修仙，只种田——可他种出的灵草，养出了后来整个山谷的体修。」', willpowerBonus: 50 },
  { id: 'tale.first-valley-settler', title: '开山祖', line: '茶客讲起开山立谷的那位祖师。「他选这片谷，是因为这里的土能种——体修的根，从开山那锄就扎下了。」', willpowerBonus: 50 },
  { id: 'tale.lost-cultivator', title: '迷修', line: '茶客讲起一位迷失了道心的灵修。「他境界高了，却忘了为何而修——体修的人，道心不在天上，在脚下的田里。」', willpowerBonus: 40 },
  { id: 'tale.fallen-immortal', title: '陨仙', line: '茶客讲起传闻中陨落在山外的仙人。「仙也会陨——体修的人看着陨仙，反倒更信自己脚下的土。」', willpowerBonus: 40 },
  { id: 'tale.broken-mount-peak', title: '断峰', line: '茶客讲起远处那座被雷劈断的山峰。「那是上古一次大劫的痕——体修的人路过，都该心存敬畏。」', willpowerBonus: 40 },
  { id: 'tale.dried-spirit-sea', title: '涸海', line: '茶客讲起传说中早已干涸的古灵海。「海能涸，何况人——体修的人，不图永盛，只图盛时多种几株好草。」', willpowerBonus: 40 },
  { id: 'tale.silent-bell', title: '哑钟', line: '茶客讲起山寺那口不再响的古钟。「钟哑了，可故事还响——体修的人，听不见的钟，也能在心里敲。」', willpowerBonus: 40 },
  { id: 'tale.forbidden-path', title: '禁路', line: '茶客讲起山谷外那条没人走的禁路。「禁的不是路，是贪——体修的人，该止则止，不贪路。」', willpowerBonus: 40 },
  { id: 'tale.father-lesson', title: '父训', line: '茶客讲起父亲当年教他握锄的那双手。「父亲的手粗，可握锄的姿势最正——体修的人，根在父辈那一代就教下了。」', willpowerBonus: 50 },
  { id: 'tale.mother-meal', title: '母饭', line: '茶客讲起母亲熬的那碗热汤。「母亲的汤比丹药养人——体修的人，最暖的不是炉火，是家里的灶头。」', willpowerBonus: 40 },
  { id: 'tale.sibling-rivalry', title: '兄弟', line: '茶客讲起和兄弟抢着干活的旧日。「兄弟争的不是谁少干，是谁多干——体修的人，有这份争，家才旺。」', willpowerBonus: 40 },
  { id: 'tale.wife-support', title: '妻扶', line: '茶客讲起妻子替他守过的那几夜棚。「她不修体修，可她守的棚比阵还稳——体修的人，背后有个人，路才走得直。」', willpowerBonus: 50 },
  { id: 'tale.grandchild-visit', title: '孙至', line: '茶客讲起孙子来棚里看他的那日。「孙子问这问那，他答着答着笑了——体修的人，传的不只是田，是这份笑。」', willpowerBonus: 40 },
  { id: 'tale.uncle-gift', title: '叔赠', line: '茶客讲起叔父送他第一把锄的事。「那把锄旧，他却用了半辈子——体修的人，长辈给的旧物，最值钱。」', willpowerBonus: 40 },
  { id: 'tale.cousin-help', title: '表助', line: '茶客讲起表兄弟来帮忙抢收的那几日。「亲戚的帮，不图钱，图情——体修的人，这份亲情是最实的后援。」', willpowerBonus: 40 },
  { id: 'tale.adopted-orphan', title: '收孤', line: '茶客讲起收养那个山谷孤儿的经过。「他不姓我，可他叫我爹——体修的人，家人不只在血，在守在一起。」', willpowerBonus: 50 },
  { id: 'tale.spring-festival-tale', title: '春社', line: '茶客讲起春社日祭土地的旧俗。「春社谢土，是一年的开头——体修的人，谢的不是神，是脚下这片让你扎根的土。」', willpowerBonus: 40 },
  { id: 'tale.summer-solstice-tale', title: '夏至祭', line: '茶客讲起夏至日祭灵脉的仪式。「夏至灵脉最旺，谢它一年的养——体修的人，连地脉的恩都记着。」', willpowerBonus: 40 },
  { id: 'tale.autumn-moon-tale', title: '秋分月', line: '茶客讲起秋分夜赏月的清雅。「秋分月最圆——体修的人，忙了一夏，这夜该歇下抬头看一看。」', willpowerBonus: 40 },
  { id: 'tale.lantern-night', title: '上元', line: '茶客讲起上元夜满棚挂灯的暖意。「上元的灯替旧年送行，替新年引路——体修的人，这夜灯火不熄。」', willpowerBonus: 40 },
  { id: 'tale.clear-bright', title: '清明', line: '茶客讲起清明去先人坟前扫土的肃穆。「清明不是哭——是告诉先人，田还在，人还在，路还接着走。」', willpowerBonus: 50 },
  { id: 'tale.double-ninth', title: '重阳', line: '茶客讲起重阳登高望整片山谷的豁达。「重阳登高，才知道自己守的这片谷有多大——体修的人，也该偶尔抬头看远。」', willpowerBonus: 40 },
  { id: 'tale.cold-food', title: '寒食', line: '茶客讲起寒食日断火吃冷食的清修。「寒食一日，清的是肠胃，也是心——体修的人，偶尔断一断，比补更养。」', willpowerBonus: 40 },
  { id: 'tale.laba', title: '腊八', line: '茶客讲起腊八熬的一锅杂粮粥。「腊八粥用尽一年的存粮——体修的人，年尾这一锅，是把一年的收成熬成一碗暖。」', willpowerBonus: 40 },
  { id: 'tale.blank-page', title: '白纸', line: '茶客讲起面对一张白纸时的清净。「白纸最难得——体修的人，心里偶尔也该清成一张白纸，重新写。」', willpowerBonus: 40 },
  { id: 'tale.left-undone', title: '留白', line: '茶客讲起画里留白的道理。「画满了就死，留白才活——体修的日子也该留白，不能填太满。」', willpowerBonus: 40 },
  { id: 'tale.half-finished', title: '半成', line: '茶客讲起那件没做完的旧工具。「它半成，搁着——体修的人，有些事不急着做完，搁一搁反而做得更好。」', willpowerBonus: 40 },
  { id: 'tale.silent-answer', title: '默答', line: '茶客讲起山谷对很多问题都不答，却都答了。「默答是最大的答——体修的人，慢慢就懂，山谷用日子答你。」', willpowerBonus: 50 },
  { id: 'tale.unwritten-poem', title: '无字诗', line: '茶客讲起棚柱上一首没写完的诗。「只两句，可意味深——体修的人，话不必说尽，诗不必写完。」', willpowerBonus: 40 },
  { id: 'tale.echo-question', title: '回声问', line: '茶客讲起问山谷的问题都成了回声。「回声是问题回到自己——体修的人，很多答案早就在问里。」', willpowerBonus: 40 },
  { id: 'tale.shadow-self', title: '影我', line: '茶客讲起月下自己的影子。「影是另一个我，它不说话，可它跟着——体修的人，影是最忠的伴。」', willpowerBonus: 40 },
  { id: 'tale.mirror-other', title: '镜他', line: '茶客讲起从别人身上看见自己的瞬间。「他是镜，照出我的短——体修的人，看人也是看己。」', willpowerBonus: 40 },
  { id: 'tale.wanderer-rumor-north', title: '北地寒原', line: '茶客转述游方散修讲的北地寒原。「那里种不出灵草，可长一种比铁还硬的冰骨草——体修的人听了，心里记下：苦寒之地，养最硬的草。」', willpowerBonus: 40 },
  { id: 'tale.wanderer-rumor-south', title: '南疆瘴林', line: '茶客转述南疆瘴林的传闻。「瘴里长的是和合叶的祖株——毒与解同根，体修的人听了，懂了相生相克。」', willpowerBonus: 40 },
  { id: 'tale.wanderer-rumor-east', title: '东海潮崖', line: '茶客转述东海潮崖的见闻。「崖上长一种吸盐的灵藻——体修的人听了，知道极境也能养出独特的灵。」', willpowerBonus: 40 },
  { id: 'tale.wanderer-rumor-west', title: '西域风漠', line: '茶客转述西域风漠的故事。「漠里偶有绿洲，长一种抗旱的粟——体修的人听了，更信绝处也有生机。」', willpowerBonus: 40 },
  { id: 'tale.wanderer-rumor-central', title: '中原古田', line: '茶客转述中原古田的传说。「那里的田种了千年——体修的人听了，知道田也能成传承。」', willpowerBonus: 40 },
  { id: 'tale.wanderer-rumor-overseas', title: '海外仙岛', line: '茶客转述海外仙岛的传闻。「岛上的灵草凡人碰不得——体修的人听了，笑笑：凡骨的田，一样能种出大道。」', willpowerBonus: 40 },
  { id: 'tale.wanderer-rumor-oldroad', title: '古道残碑', line: '茶客转述古道残碑上的字。「碑文记的是一位古农的种田诀——体修的人听了，把这几句记进了心里。」', willpowerBonus: 50 },
  { id: 'tale.wanderer-rumor-starsea', title: '星海遥望', line: '茶客转述夜里遥望星海的感觉。「星海比灵海还远——体修的人听了，知道飞升之外还有更远的，可脚下这锄最实。」', willpowerBonus: 40 },
  { id: 'tale.beast-old-faithful', title: '老义兽', line: '茶客讲起那只守了三代田的老巡守兽。「它比棚还老——体修的人，兽的忠比人的话还可靠。」', willpowerBonus: 50 },
  { id: 'tale.beast-pup-training', title: '幼训', line: '茶客讲起训幼兽要从一声哨开始。「哨声是它的第一个字——体修的人，训兽也像教子，急不得。」', willpowerBonus: 40 },
  { id: 'tale.beast-injury', title: '兽伤', line: '茶客讲起巡守兽护田受的伤。「它替你挡了一下——体修的人，兽的伤，比自己的伤更心疼。」', willpowerBonus: 40 },
  { id: 'tale.beast-bond-deep', title: '深羁', line: '茶客讲起和兽默契到不用哨的那天。「一个眼神它就懂——体修的人，这份深羁，是夜夜守出来的。」', willpowerBonus: 50 },
  { id: 'tale.courier-long-trip', title: '跑长路', line: '茶客讲起递送兽替他跑过的最远一趟。「它跑了三天三夜——体修的人，递送兽的耐力，是养出来的。」', willpowerBonus: 40 },
  { id: 'tale.courier-storm', title: '冒雨', line: '茶客讲起递送兽冒雨送到的灵种。「湿透了，可种没坏——体修的人，递送兽的稳，雨浇不散。」', willpowerBonus: 40 },
  { id: 'tale.field-ward-night', title: '守田夜', line: '茶客讲起守田兽整夜巡田的影。「它在田埂上走了一宿——体修的人，有它守着，这夜才睡得实。」', willpowerBonus: 40 },
  { id: 'tale.array-warden-stake', title: '阵守桩', line: '茶客讲起阵守兽蹲在阵眼上不动的那份稳。「它替阵定心——体修的人，阵守兽是阵的另一根桩。」', willpowerBonus: 40 },
  { id: 'tale.pill-fire-control', title: '控火', line: '茶客讲起炼丹控火的难。「火急了炸，火缓了散——体修的人，控的不是火，是自己的性子。」', willpowerBonus: 40 },
  { id: 'tale.pill-property-balance', title: '药性衡', line: '茶客讲起药性平衡的巧。「寒热要相制，不是相灭——体修的人，平衡是活，不是死。」', willpowerBonus: 40 },
  { id: 'tale.pill-poison-taming', title: '伏毒', line: '茶客讲起丹毒伏而用的法门。「毒不是弃——伏住了，毒也能成药；体修的人，连毒都敢用。」', willpowerBonus: 50 },
  { id: 'tale.pill-failed-batch', title: '败炉', line: '茶客讲起败了一炉丹的那夜。「炉渣也留着——体修的人，败炉里也有一半的学问。」', willpowerBonus: 40 },
  { id: 'tale.pill-master-piece', title: '成丹', line: '茶客讲起头一次出绝品丹的喜悦。「那枚丹泛着宝光——体修的人，那一刻所有的炸炉都值了。」', willpowerBonus: 50 },
  { id: 'tale.furnace-temper', title: '炼炉', line: '茶客讲起养丹炉像养孩子的耐心。「炉越养越熟它的脾气——体修的人，自己的炉自己最懂。」', willpowerBonus: 40 },
  { id: 'tale.herb-prep', title: '制药', line: '茶客讲起制药前净料的那份细。「一颗土粒毁一炉丹——体修的人，制药先净心净料。」', willpowerBonus: 40 },
  { id: 'tale.catalyst-trick', title: '引子', line: '茶客讲起加引子的火候。「引子早了晚都不行——体修的人，那一指头的工夫，是全炉的命门。」', willpowerBonus: 40 },
  { id: 'tale.array-draft', title: '画阵', line: '茶客讲起画阵纹那份静。「手一抖，纹就歪——体修的人，画阵就是练定力。」', willpowerBonus: 40 },
  { id: 'tale.array-core-tune', title: '调核', line: '茶客讲起调阵核像调弦。「核松了阵弱，核紧了阵崩——体修的人，调的是恰到好处。」', willpowerBonus: 40 },
  { id: 'tale.array-coverage', title: '覆阵', line: '茶客讲起布阵覆盖的算计。「覆太宽力薄，覆太窄漏角——体修的人，覆盖是算出来的，不是拍脑袋。」', willpowerBonus: 40 },
  { id: 'tale.array-power-flow', title: '通流', line: '茶客讲起阵纹通不通流的检验。「纹通则灵机流，纹断则阵死——体修的人，通流是阵的命脉。」', willpowerBonus: 40 },
  { id: 'tale.array-repair-tale', title: '补阵', line: '茶客讲起雷季后补阵的习惯。「阵总有一处先松——体修的人，补得勤，阵才不崩。」', willpowerBonus: 40 },
  { id: 'tale.array-resonance', title: '共振', line: '茶客讲起阵与巡守兽共振的那一下。「阵守兽一进位，阵就活了——体修的人，这份共振是阵的魂。」', willpowerBonus: 50 },
  { id: 'tale.array-broken-talisman-input', title: '投料', line: '茶客讲起往阵里投破损法宝的讲究。「料要对位——错位的料不是养阵，是伤阵；体修的人，投料讲究。」', willpowerBonus: 40 },
  { id: 'tale.array-spirit-stone-fuel', title: '供灵', line: '茶客讲起用灵石给阵续灵。「阵耗灵石，可省的是人命——体修的人，这份灵石花得值。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-tend', title: '养棚', line: '茶客讲起养棚那份日日的功夫。「棚是一日一日养出来的——体修的人，养棚和养身一个理。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-vent', title: '通气', line: '茶客讲起开棚窗通气的时辰。「气闷了苗就蔫——体修的人，知道哪个时辰该开哪扇窗。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-water', title: '润棚', line: '茶客讲起润棚的水量。「水少了干，水多了烂——体修的人，润棚的水要像自己的呼吸一样准。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-shade', title: '遮阴', line: '茶客讲起盛夏给棚遮阴的布。「阴布一拉，苗就不晒——体修的人，连光都替苗省着。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-prop', title: '支苗', line: '茶客讲起给倒伏的灵苗支棍的事。「一根细棍扶住一株苗——体修的人，细处见功夫。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-soil', title: '换土', line: '茶客讲起给棚换新土的年份。「土养几年就薄了——体修的人，换土是给棚续命。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-pest', title: '除虫', line: '茶客讲起夜里挑灯除虫的烦。「虫小可不能小看——体修的人，除虫比除妖还勤。」', willpowerBonus: 40 },
  { id: 'tale.greenhouse-prune', title: '修枝', line: '茶客讲起给灵苗修枝的巧。「该剪的不心疼——体修的人，修枝是为了让苗往该长的方向长。」', willpowerBonus: 40 },
  { id: 'tale.farm-till-depth', title: '深耕', line: '茶客讲起深耕的讲究。「浅翻养表，深翻养根——体修的人，翻地舍得下力气，根才扎得深。」', willpowerBonus: 40 },
  { id: 'tale.farm-water-time', title: '浇时', line: '茶客讲起浇水的时辰。「晨浇醒苗，暮浇润根——体修的人，浇水看时辰，比看水量还紧。」', willpowerBonus: 40 },
  { id: 'tale.farm-harvest-stage', title: '收候', line: '茶客讲起等灵草药性到点再收的耐性。「急收药性散，等收药性聚——体修的人，收候比种还考验耐性。」', willpowerBonus: 40 },
  { id: 'tale.farm-weed', title: '除草', line: '茶客讲起和杂草较劲的日常。「草抢的是灵苗的肥——体修的人，除草不是闲事，是护灵。」', willpowerBonus: 40 },
  { id: 'tale.farm-fertilize', title: '施肥', line: '茶客讲起施肥薄而勤的法门。「一次施足烧根，薄肥勤施才养——体修的人，养苗如养身，过犹不及。」', willpowerBonus: 40 },
  { id: 'tale.farm-rotate', title: '轮作', line: '茶客讲起轮作养地的道理。「一茬灵草一茬凡作——体修的人，轮着种，地才不累。」', willpowerBonus: 40 },
  { id: 'tale.farm-fallow', title: '休耕', line: '茶客讲起让一块田歇一年的智慧。「歇一年，来年肥两年——体修的人，懂得让田歇，也懂得让自己歇。」', willpowerBonus: 40 },
  { id: 'tale.farm-protect', title: '护田', line: '茶客讲起护田不只是防兽。「防兽、防风、防涝、防旱——体修的人，护田是全天候的活。」', willpowerBonus: 40 },
  { id: 'tale.storage-sort', title: '分仓', line: '茶客讲起把仓分门别类的规矩。「分得清，急用时就不慌——体修的仓，乱一点就误事。」', willpowerBonus: 40 },
  { id: 'tale.storage-label', title: '贴签', line: '茶客讲起给每袋存料贴签的习惯。「签一贴，就不会拿错——体修的人，这点细心省的是命。」', willpowerBonus: 40 },
  { id: 'tale.storage-rotate-stock', title: '陈新', line: '茶客讲起先用陈料、后用新料的讲究。「陈的先用了才不坏——体修的人，存货也讲先来后到。」', willpowerBonus: 40 },
  { id: 'tale.storage-protect-moist', title: '防潮', line: '茶客讲起仓底垫石防潮的法子。「潮一进，料就霉——体修的人，防潮比防贼还紧。」', willpowerBonus: 40 },
  { id: 'tale.storage-protect-pest', title: '防蛀', line: '茶客讲起仓里熏驱虫药的门道。「虫蛀的料废一半——体修的人，防蛀是存料的第一关。」', willpowerBonus: 40 },
  { id: 'tale.storage-count', title: '盘库', line: '茶客讲起每月盘一次库的习惯。「盘一盘，心里才有数——体修的人，不盘库的，日子是糊涂账。」', willpowerBonus: 40 },
  { id: 'tale.storage-rare', title: '藏珍', line: '茶客讲起仓里那只藏绝品丹的暗格。「珍物不常示人——体修的人，藏珍是给自己留的底牌。」', willpowerBonus: 40 },
  { id: 'tale.storage-share', title: '分邻', line: '茶客讲起灾年把仓底分给邻的事。「分出去救了人——体修的人，仓不只是自己的，是山谷的。」', willpowerBonus: 50 },
  { id: 'tale.stage-foundation', title: '筑基', line: '茶客讲起头一阶打地基的笨功夫。「地基不牢，楼再高也虚——体修的筑基，就是一锄一锄把凡骨的根扎进土里。」', willpowerBonus: 40 },
  { id: 'tale.stage-bone-forging', title: '锻骨', line: '茶客讲起锻骨那阶的痛与长。「骨要锻得响——每一锤下去，都是凡骨往铁骨挪一寸。」', willpowerBonus: 40 },
  { id: 'tale.stage-marrow-wash', title: '洗髓', line: '茶客讲起洗髓时骨里发痒的感觉。「痒比痛还难熬——可熬过去，骨里就清了；体修的人，洗髓是清根。」', willpowerBonus: 40 },
  { id: 'tale.stage-blood-coagulate', title: '凝血', line: '茶客讲起凝血那阶气血沉下去的踏实。「血凝住了，就不浮——体修的人，血沉丹田，人才稳。」', willpowerBonus: 40 },
  { id: 'tale.stage-thunder-bone', title: '雷骨', line: '茶客讲起雷骨那阶的底气。「雷骨长成，雷就不那么怕了——体修的人，这一阶是命换来的。」', willpowerBonus: 50 },
  { id: 'tale.stage-purple-tribulation', title: '紫雷阶', line: '茶客讲起紫雷阶那条独木桥。「走过去是飞升，走不过是留世——体修的人，紫雷阶不求生，只求不愧。」', willpowerBonus: 50 },
  { id: 'tale.body-temper', title: '淬体', line: '茶客讲起淬体不是一时的功。「淬体是日积月累——体修的人，把每天的日子都当一炉淬火的柴。」', willpowerBonus: 40 },
  { id: 'tale.endurance-build', title: '韧骨', line: '茶客讲起韧比刚更要紧的道理。「刚的易折，韧的难断——体修的人，骨要刚，更要韧。」', willpowerBonus: 40 },
  { id: 'tale.commission-herb', title: '药草单', line: '茶客讲起接药草委托的稳当。「药草单最稳——体修的人，先把这类单做扎实，名声就起来了。」', willpowerBonus: 40 },
  { id: 'tale.commission-beast', title: '妖兽单', line: '茶客讲起接妖兽委托的险。「妖兽单酬高可险——体修的人，接前先掂量自己的阵和兽够不够。」', willpowerBonus: 40 },
  { id: 'tale.commission-array', title: '阵材单', line: '茶客讲起接阵材委托的细。「阵材单要的东西杂——体修的人，平时多囤碎件，接单才不慌。」', willpowerBonus: 40 },
  { id: 'tale.special-order-urgent', title: '急单', line: '茶客讲起接急单的取舍。「急单酬厚可赶——体修的人，接急单前先问自己累不累，累就别接。」', willpowerBonus: 40 },
  { id: 'tale.special-order-reward', title: '厚酬', line: '茶客讲起那份厚酬单背后的考校。「酬厚往往有坎——体修的人，厚酬面前更要稳。」', willpowerBonus: 40 },
  { id: 'tale.special-order-repeat', title: '回头客', line: '茶客讲起把单做漂亮换来的回头客。「回头客比新客值钱——体修的人，一单做扎实，等于十单。」', willpowerBonus: 40 },
  { id: 'tale.special-order-failed', title: '误单', line: '茶客讲起当年误了一单的教训。「误单比不接还伤名——体修的人，接了就一定得交。」', willpowerBonus: 40 },
  { id: 'tale.special-order-rare', title: '稀单', line: '茶客讲起那份罕见的稀单。「稀单一辈子碰不了几回——体修的人，碰上了是缘，做成了是命。」', willpowerBonus: 50 },
  { id: 'tale.ruin-first-step', title: '遗迹初探', line: '茶客讲起头一回踏进山谷遗迹的紧张。「那扇门像在筛人——体修的人，踏进去那一步，就把自己交给了更深的考验。」', willpowerBonus: 40 },
  { id: 'tale.ruin-deep-fear', title: '深处惧', line: '茶客讲起遗迹深处那股无名的惧。「越深，惧越重——体修的人，这份惧不是怕，是遗迹在试你的心。」', willpowerBonus: 40 },
  { id: 'tale.ruin-old-trap', title: '古阱', line: '茶客讲起遗迹里那些上古留下的阱。「阱不杀灵修，专困体修——体修的人，在遗迹里每步都得看清楚。」', willpowerBonus: 40 },
  { id: 'tale.ruin-talisman-find', title: '拾残', line: '茶客讲起在遗迹拾到破损法宝的运气。「那是前人留下的命——体修的人，拾了就替前人接着走。」', willpowerBonus: 40 },
  { id: 'tale.ruin-chapter-bone', title: '裂骨章', line: '茶客讲起遗迹前五层像在筛骨。「裂骨试阶——体修的人，扛过这五层，才算有资格往深处。」', willpowerBonus: 40 },
  { id: 'tale.ruin-chapter-array', title: '残阵章', line: '茶客讲起遗迹第六到十层的断阵纹。「那是前人留给体修的逆推题——算得清的，阵就成自己的。」', willpowerBonus: 40 },
  { id: 'tale.ruin-chapter-beast', title: '妖痕章', line: '茶客讲起遗迹深处的妖兽抓痕。「那里从不是灵修的传承——体修的人，看见这些痕，反倒觉得亲切。」', willpowerBonus: 40 },
  { id: 'tale.ruin-heaven-gate', title: '逆命门', line: '茶客讲起遗迹最深处的逆命门。「门后残留着引劫痕——体修的人，到这里才知道，前人替你试过这条路。」', willpowerBonus: 50 },
  { id: 'tale.herb-gatherer-deep', title: '药女深处', line: '茶客讲起采药女带他进过的那片秘药圃。「她只带真信得过的人——体修的人，被带进去那刻，就知道这份交情到了底。」', willpowerBonus: 50 },
  { id: 'tale.array-smith-deep', title: '阵匠深处', line: '茶客讲起阵匠老陆给他看过的那卷不传阵图。「图上都是体修的阵路——体修的人，看到这卷，等于接了半个传承。」', willpowerBonus: 50 },
  { id: 'tale.wanderer-deep', title: '散修深处', line: '茶客讲起游方散修喝醉后吐露的外乡秘闻。「他平时不说的——体修的人，这份酒后真言，比清醒时还实。」', willpowerBonus: 40 },
  { id: 'tale.npc-birthday', title: '生辰', line: '茶客讲起给山谷朋友过生辰的习惯。「生辰不送礼，只上门坐坐——体修的人，记得朋友的生辰，比送礼还重。」', willpowerBonus: 40 },
  { id: 'tale.npc-gift-return', title: '回礼', line: '茶客讲起受人恩必回礼的规矩。「回礼不是还债，是续交情——体修的人，礼尚往来，路才走得长。」', willpowerBonus: 40 },
  { id: 'tale.npc-secret', title: '私语', line: '茶客讲起朋友私下告诉他的心事。「私语是信——体修的人，替朋友守这份私语，比守阵还严。」', willpowerBonus: 40 },
  { id: 'tale.npc-farewell', title: '暂别', line: '茶客讲起朋友远行时的送别。「送别不哭，只叮嘱——体修的人，知道山谷的人总会再回来。」', willpowerBonus: 40 },
  { id: 'tale.npc-reunion', title: '重逢', line: '茶客讲起多年后朋友回山重逢的喜。「重逢比初识还暖——体修的人，这份久别重逢，是留世才有的福。」', willpowerBonus: 50 },
  { id: 'tale.incident-beast-trace', title: '妖痕事', line: '茶客讲起处置田埂妖兽痕的那夜。「补上内丹药引，免得它再来——体修的人，处置这种事，最忌拖。」', willpowerBonus: 40 },
  { id: 'tale.incident-array-fray', title: '阵松事', line: '茶客讲起村口旧阵又松了一处。「补上破损法宝压稳阵脚——体修的人，阵松了就补，别等它崩。」', willpowerBonus: 40 },
  { id: 'tale.incident-seasonal', title: '节灾事', line: '茶客讲起反季寒流夜扫灵田的事。「借棚里微气候，再培根固本——体修的人，节灾靠的是提前养好的棚。」', willpowerBonus: 40 },
  { id: 'tale.incident-tribute', title: '供奉事', line: '茶客讲起镇上祭坛要灵石献祭的事。「备好灵石办稳——体修的人，这份供奉是山谷认你的另一条路。」', willpowerBonus: 40 },
  { id: 'tale.incident-hermit', title: '隐士事', line: '茶客讲起云游隐士登门论道求残卷的事。「以残卷相赠，换一份论道——体修的人，这份交道比灵石还值。」', willpowerBonus: 40 },
  { id: 'tale.incident-merchant', title: '商队事', line: '茶客讲起远来商队缺干粮求灵草的事。「接济一把，结个善缘——体修的人，商队的传名比酬金远。」', willpowerBonus: 40 },
  { id: 'tale.incident-frost', title: '霜害事', line: '茶客讲起夜里骤霜扫过灵田的事。「以露根草覆根御寒——体修的人，霜害靠的是手快和存料足。」', willpowerBonus: 40 },
  { id: 'tale.incident-miasma', title: '瘴气事', line: '茶客讲起残脉深处渗出瘴气伤苗的事。「以和合叶化浊解毒——体修的人，瘴气靠的是常备解药。」', willpowerBonus: 40 },
  { id: 'tale.celestial-cloud', title: '云相', line: '茶客讲起看云相料天气的老法子。「云厚云薄，各有说头——体修的人，看云比看卜准。」', willpowerBonus: 40 },
  { id: 'tale.celestial-star', title: '星相', line: '茶客讲起夜里看星相辨时令的习惯。「星移换季——体修的人，星相是另一本日历。」', willpowerBonus: 40 },
  { id: 'tale.celestial-moon-phase', title: '月相', line: '茶客讲起按月相安排农事的传统。「月圆收、月缺种——体修的人，月相是种田的节拍。」', willpowerBonus: 40 },
  { id: 'tale.celestial-wind-direction', title: '风向', line: '茶客讲起辨风向料阴晴的本事。「东风雨、西风晴——体修的人，风向是天的暗示。」', willpowerBonus: 40 },
  { id: 'tale.celestial-rainbow', title: '虹兆', line: '茶客讲起雨后彩虹的吉兆。「虹是雨后的答谢——体修的人，看见虹，就知道这阵雨没白下。」', willpowerBonus: 40 },
  { id: 'tale.celestial-halo', title: '晕兆', line: '茶客讲起日晕月晕的征兆。「晕是风雨的前奏——体修的人，看见晕，就该提前备棚。」', willpowerBonus: 40 },
  { id: 'tale.celestial-shooting-star', title: '流星', line: '茶客讲起夜空划过的流星。「流星是天的眨眼——体修的人，看见流星，许个种好田的愿。」', willpowerBonus: 40 },
  { id: 'tale.celestial-eclipse', title: '蚀兆', line: '茶客讲起日蚀月蚀的肃穆。「蚀是天暂闭眼——体修的人，蚀时不出田，静守过这一刻。」', willpowerBonus: 40 },
  { id: 'tale.tool-hoe-tale', title: '锄', line: '茶客讲起锄是体修最亲的伙伴。「它不说话，可替你把每一寸土翻透——体修的人，锄用久了，比手还听使唤。」', willpowerBonus: 40 },
  { id: 'tale.tool-pail-tale', title: '桶', line: '茶客讲起灵水桶提了多少年的水。「一桶一桶浇出的田——体修的人，桶的分量，肩最清楚。」', willpowerBonus: 40 },
  { id: 'tale.tool-sickle-tale', title: '镰', line: '茶客讲起镰刃要常磨的规矩。「镰利，收得快——体修的人，磨镰的半日，是省秋收的半日。」', willpowerBonus: 40 },
  { id: 'tale.tool-whistle-tale', title: '哨', line: '茶客讲起驯兽哨用了多少年。「哨声是和兽的暗号——体修的人，一只哨用一生，兽也认一生。」', willpowerBonus: 40 },
  { id: 'tale.tool-rod-tale', title: '钓', line: '茶客讲起闲时在溪边垂钓的清净。「钓不为鱼——体修的人，钓的是那一刻心静。」', willpowerBonus: 40 },
  { id: 'tale.tool-net-tale', title: '网', line: '茶客讲起灵网补了又补的耐心。「网是活的——体修的人，补网也是补自己的耐性。」', willpowerBonus: 40 },
  { id: 'tale.tool-lamp-tale', title: '灯', line: '茶客讲起守夜那盏不灭的油灯。「灯亮着，心就不慌——体修的人，守夜的灯，是田头另一双眼睛。」', willpowerBonus: 40 },
  { id: 'tale.tool-bell-tale', title: '铃', line: '茶客讲起挂在棚口的旧铃铛。「风一过它就响——体修的人，这铃声替你听风的来去。」', willpowerBonus: 40 },
  { id: 'tale.spring-activity', title: '春事', line: '茶客讲起一年之计在于春的体修版。「春是头一锄——体修的人，这一锄下得好，全年都顺。」', willpowerBonus: 40 },
  { id: 'tale.summer-activity', title: '夏事', line: '茶客讲起盛夏护棚防暑的辛劳。「夏最熬人——体修的人，三伏天守的就是棚里那几度温差。」', willpowerBonus: 40 },
  { id: 'tale.autumn-activity', title: '秋事', line: '茶客讲起秋收最忙的那段日子。「秋是收成也是结算——体修的人，秋里忙，可忙得心里实。」', willpowerBonus: 40 },
  { id: 'tale.winter-activity', title: '冬事', line: '茶客讲起冬藏养蓄的传统。「冬是歇也是养——体修的人，冬里养好了，来春才有力。」', willpowerBonus: 40 },
  { id: 'tale.new-year-plan', title: '岁计', line: '茶客讲起年初盘算一年的习惯。「计不空——体修的人，年初盘清楚，全年不慌。」', willpowerBonus: 40 },
  { id: 'tale.end-of-year-review', title: '岁盘', line: '茶客讲起年尾复盘得失的智慧。「盘不是悔——体修的人，年尾盘清楚了，来年才更进一步。」', willpowerBonus: 40 },
  { id: 'tale.mid-year-reminder', title: '半载', line: '茶客讲起年中提醒自己别松懈的规矩。「半载一过，最易松——体修的人，年中这一提醒，是续命的鞭。」', willpowerBonus: 40 },
  { id: 'tale.season-transition', title: '换季', line: '茶客讲起换季时田里棚里的调整。「换季是关——体修的人，换季换法，跟着天走，田才不脱节。」', willpowerBonus: 40 },
  { id: 'tale.proverb-still-water', title: '静水深', line: '茶客讲起静水深流的道理。「最静的水流得最深——体修的人，话少事多，是这份静。」', willpowerBonus: 40 },
  { id: 'tale.proverb-late-bloomer', title: '晚成', line: '茶客讲起大器晚成的安慰。「有些灵草慢熟——体修的人，不嫌慢，晚成的往往最沉。」', willpowerBonus: 40 },
  { id: 'tale.proverb-empty-vessel', title: '空器', line: '茶客讲起空器响、满器默的老话。「半瓶水才晃——体修的人，越满越静。」', willpowerBonus: 40 },
  { id: 'tale.proverb-deep-root-silent', title: '深根默', line: '茶客讲起深根不语的智慧。「根深的不嚷——体修的人，根扎稳了，不用张扬。」', willpowerBonus: 40 },
  { id: 'tale.proverb-sharp-bark-dull', title: '锐声钝', line: '茶客讲起锐声钝斧的道理。「叫得响的往往钝——体修的人，看人看工具，别被声唬了。」', willpowerBonus: 40 },
  { id: 'tale.proverb-soft-persist', title: '柔久', line: '茶客讲起柔能久存的道理。「刚的易折，柔的久存——体修的人，外圆内方，才能走得长。」', willpowerBonus: 40 },
  { id: 'tale.proverb-high-fall-low-rise', title: '高坠低起', line: '茶客讲起高坠低起的轮回。「越高越险，越低越稳——体修的人，宁低勿虚。」', willpowerBonus: 40 },
  { id: 'tale.proverb-many-small', title: '聚沙', line: '茶客讲起聚沙成塔的耐性。「一点一滴攒——体修的人，不轻视小，小攒多了就是大。」', willpowerBonus: 40 },
  { id: 'tale.life-contentment', title: '知足', line: '茶客讲起知足常乐的体修版。「田够种、饭够吃、日子够稳——体修的人，知足的，反而走得最远。」', willpowerBonus: 40 },
  { id: 'tale.life-simplicity', title: '素朴', line: '茶客讲起素朴过日的清净。「不攀不比——体修的人，活得素朴，心就清明。」', willpowerBonus: 40 },
  { id: 'tale.life-honesty', title: '本分', line: '茶客讲起守本分的踏实。「该干嘛干嘛——体修的人，守本分，不生非分之想，路才直。」', willpowerBonus: 40 },
  { id: 'tale.life-diligence', title: '勤', line: '茶客讲起勤能补拙的信念。「灵根没有，勤来补——体修的人，这份勤，是凡骨唯一的根。」', willpowerBonus: 40 },
  { id: 'tale.life-prudence', title: '慎', line: '茶客讲起慎言慎行的老成。「一步三思——体修的人，慎着走，比急着跑活得久。」', willpowerBonus: 40 },
  { id: 'tale.life-courage', title: '勇', line: '茶客讲起勇于面对的真勇。「不是不怕，是怕了还上——体修的人，引劫那一刻的勇，是真勇。」', willpowerBonus: 50 },
  { id: 'tale.life-wisdom', title: '智', line: '茶客讲起智在知止的智慧。「智不是懂多——体修的人，智在知道什么时候该止。」', willpowerBonus: 40 },
  { id: 'tale.life-kindness', title: '仁', line: '茶客讲起仁者无敌的体修解。「仁不是弱——体修的人，仁是连田里的苗都爱惜，这份仁养出的是厚道。」', willpowerBonus: 40 },
  { id: 'tale.state-calm', title: '静', line: '茶客讲起心静如水的体修境。「静是体修的底色——心静了，雷声都成了背景。」', willpowerBonus: 40 },
  { id: 'tale.state-quiet', title: '寂', line: '茶客讲起独守山谷的那份寂。「寂不等于孤——体修的人，享受这份寂，是修行的福。」', willpowerBonus: 40 },
  { id: 'tale.state-peace', title: '宁', line: '茶客讲起夜里田安宁的那份踏实。「宁是田给的——体修的人，田宁心就宁。」', willpowerBonus: 40 },
  { id: 'tale.state-joy', title: '悦', line: '茶客讲起日常小事里的悦。「一株新芽、一窝新兽——体修的人，悦在小事里，比大喜还养神。」', willpowerBonus: 40 },
  { id: 'tale.state-sorrow', title: '哀', line: '茶客讲起失去时的那份哀。「哀要过——体修的人，不压哀，过完它，才能继续种田。」', willpowerBonus: 40 },
  { id: 'tale.state-anger', title: '怒', line: '茶客讲起怒时先停手的规矩。「怒里不出手——体修的人，怒了先坐一会，比出错后悔强。」', willpowerBonus: 40 },
  { id: 'tale.state-fear', title: '惧', line: '茶客讲起对雷劫的那份惧。「有惧是好事——体修的人，带着惧去引劫，比盲目自信活得久。」', willpowerBonus: 40 },
  { id: 'tale.state-hope', title: '望', line: '茶客讲起留世之人心里那点望。「望不在飞升，在明天的田——体修的人，这点望，是日子的火种。」', willpowerBonus: 50 },
  { id: 'tale.color-ink', title: '墨色', line: '茶客讲起山谷里最常见的那抹墨色。「墨色不张扬——体修的人，日子是墨色的，沉、稳、养人。」', willpowerBonus: 40 },
  { id: 'tale.color-gold', title: '灵金', line: '茶客讲起灵石泛的那点灵金。「灵金不刺眼——体修的人，这点金，是山谷给勤人的回响。」', willpowerBonus: 40 },
  { id: 'tale.color-jade', title: '青', line: '茶客讲起灵草初生的那抹青。「青是生——体修的人，最爱这抹青，它代表田还活着。」', willpowerBonus: 40 },
  { id: 'tale.color-cinnabar', title: '朱', line: '茶客讲起丹炉里那点朱红。「朱是火——体修的人，炼丹看这抹朱，知道火候到没到。」', willpowerBonus: 40 },
  { id: 'tale.color-indigo', title: '靛', line: '茶客讲起深夜天边那抹靛蓝。「靛是深的——体修的人，靛色天最静，守夜的人最爱。」', willpowerBonus: 40 },
  { id: 'tale.color-frost-white', title: '霜白', line: '茶客讲起晨霜铺田的那片白。「霜白是警——体修的人，看见这白，就知道该护苗了。」', willpowerBonus: 40 },
  { id: 'tale.color-earth-brown', title: '土褐', line: '茶客讲起新翻泥土的那片褐。「褐是根——体修的人，褐色的土最实，根扎得最稳。」', willpowerBonus: 40 },
  { id: 'tale.color-spirit-purple', title: '灵紫', line: '茶客讲起紫雷将临时天边那抹紫。「灵紫是劫——体修的人，看见这紫，心反倒定了，因为该来的总要来。」', willpowerBonus: 50 },
  { id: 'tale.number-one', title: '一', line: '茶客讲起万事从一起的道理。「一是根——体修的人，守好这一锄一碗一田，路就有了起点。」', willpowerBonus: 40 },
  { id: 'tale.number-two', title: '二', line: '茶客讲起阴阳成双的平衡。「田有阴阳——体修的人，凡事找两面，不偏不废。」', willpowerBonus: 40 },
  { id: 'tale.number-three', title: '三', line: '茶客讲起天地人三才的体修解。「天给雷、地给土、人给勤——体修的人，三才缺一不可。」', willpowerBonus: 40 },
  { id: 'tale.number-four', title: '四', line: '茶客讲起四时轮转的节律。「四时是天的呼吸——体修的人，跟着四时走，田就顺。」', willpowerBonus: 40 },
  { id: 'tale.number-five', title: '五', line: '茶客讲起五行相生的智慧。「金木水火土——体修的人，灵草也分五行，相生才能养。」', willpowerBonus: 40 },
  { id: 'tale.number-ten', title: '十', line: '茶客讲起十全难求的现实。「十全十美是虚——体修的人，求八九分就够，留一二分给天。」', willpowerBonus: 40 },
  { id: 'tale.number-hundred', title: '百', line: '茶客讲起百年如一日的耐性。「百年不长——体修的人，把日子过成百年的节，就不慌了。」', willpowerBonus: 40 },
  { id: 'tale.number-thousand', title: '千', line: '茶客讲起千里始于足下的古训。「千里不远——体修的人，脚下这一步最实，千里自然到。」', willpowerBonus: 40 },
  { id: 'tale.direction-east', title: '东', line: '茶客讲起日出的东方是生发之位。「东位养青——体修的人，春棚朝东，苗醒得最早。」', willpowerBonus: 40 },
  { id: 'tale.direction-south', title: '南', line: '茶客讲起南向最暖的道理。「南位养暖——体修的人，喜阳的灵草朝南种，长得最旺。」', willpowerBonus: 40 },
  { id: 'tale.direction-west', title: '西', line: '茶客讲起日落西方是收敛之位。「西位养收——体修的人，秋果朝西，药性收得最足。」', willpowerBonus: 40 },
  { id: 'tale.direction-north', title: '北', line: '茶客讲起北向最阴最稳。「北位养藏——体修的人，喜阴耐寒的灵草朝北，过冬最稳。」', willpowerBonus: 40 },
  { id: 'tale.direction-up', title: '上', line: '茶客讲起往上是天的道理。「上不求——体修的人，不仰望天求，只脚踏实地。」', willpowerBonus: 40 },
  { id: 'tale.direction-down', title: '下', line: '茶客讲起往下是根的道理。「下是根——体修的人，往下扎，比往上攀实在。」', willpowerBonus: 40 },
  { id: 'tale.direction-center', title: '中', line: '茶客讲起守中道的智慧。「中是不偏——体修的人，凡事守个中，不偏激就长久。」', willpowerBonus: 40 },
  { id: 'tale.direction-return', title: '归', line: '茶客讲起万物归土的体修信。「归是终——体修的人，从土里来，回土里去，这一圈圆满。」', willpowerBonus: 50 },
  { id: 'tale.sound-wind-in-pines', title: '松涛', line: '茶客讲起山风过松林的涛声。「涛声最阔——体修的人，听一会涛，心就跟着大了。」', willpowerBonus: 40 },
  { id: 'tale.sound-rain-on-leaves', title: '雨打叶', line: '茶客讲起雨打灵草叶的细响。「这是田在喝——体修的人，听这响，比听乐还舒坦。」', willpowerBonus: 40 },
  { id: 'tale.sound-crickets', title: '虫鸣', line: '茶客讲起秋夜虫鸣的合唱。「虫鸣是秋的底乐——体修的人，有这鸣陪着，秋夜不冷清。」', willpowerBonus: 40 },
  { id: 'tale.sound-bell-toll', title: '钟声', line: '茶客讲起远处山寺的钟声。「钟声一响，万事皆轻——体修的人，这钟是给心松绑的。」', willpowerBonus: 40 },
  { id: 'tale.sound-water-flow', title: '泉流', line: '茶客讲起山泉叮咚的清响。「泉流最清心——体修的人，烦了去听一会泉，就静了。」', willpowerBonus: 40 },
  { id: 'tale.sound-fire-crackle', title: '柴爆', line: '茶客讲起炉里柴火爆裂的噼啪。「柴爆是炉在唱歌——体修的人，这响伴着炼丹，不孤单。」', willpowerBonus: 40 },
  { id: 'tale.sound-beast-purr', title: '兽鼾', line: '茶客讲起巡守兽睡熟的鼾声。「兽鼾是安心——体修的人，听见这鼾，就知道今夜田有人守。」', willpowerBonus: 40 },
  { id: 'tale.sound-snow-fall', title: '雪落', line: '茶客讲起大雪夜万籁俱寂的那份静。「雪落无声，是最大的声——体修的人，这夜最静，也最满。」', willpowerBonus: 50 },
  { id: 'tale.fate-accept', title: '认命', line: '茶客讲起认命不是躺平的道理。「认命是认清楚——体修的人，认了凡骨的命，反倒活得最用力。」', willpowerBonus: 40 },
  { id: 'tale.fate-change', title: '改命', line: '茶客讲起体修就是逆天改命。「命能改——体修的人，每一锄、每一炉，都在改命。」', willpowerBonus: 50 },
  { id: 'tale.fate-weave', title: '织命', line: '茶客讲起日子像织布，一梭一梭织出命。「命是织出来的——体修的人，把日子织结实，命就稳。」', willpowerBonus: 40 },
  { id: 'tale.time-flow', title: '时流', line: '茶客讲起时间像水流，留不住。「时流不返——体修的人，不追悔过去，只过好当下这一刻。」', willpowerBonus: 40 },
  { id: 'tale.time-still', title: '时凝', line: '茶客讲起专注时时间凝固的感觉。「时凝是入道——体修的人，干活到忘时，就摸到了道的边。」', willpowerBonus: 50 },
  { id: 'tale.space-vast', title: '空阔', line: '茶客讲起抬头看天时的空阔感。「空阔让心大——体修的人，偶尔抬头，心就不困在田里。」', willpowerBonus: 40 },
  { id: 'tale.space-intimate', title: '空亲', line: '茶客讲起低头看一株苗时的亲近感。「一株苗也是一个世界——体修的人，低头的亲近，比抬头还深。」', willpowerBonus: 40 },
  { id: 'tale.dao-silent', title: '道默', line: '茶客讲起大道无言的真意。「道不说——体修的人，用一辈子的种田，去听这道无声的话。」', willpowerBonus: 50 },
  { id: 'tale.cycle-day', title: '日轮', line: '茶客讲起日升日落的轮转。「日轮不息——体修的人，跟着日轮作息，是最朴素的道。」', willpowerBonus: 40 },
  { id: 'tale.cycle-month', title: '月轮', line: '茶客讲起月圆月缺的轮转。「月轮有盈亏——体修的人，懂盈亏，不强求常圆。」', willpowerBonus: 40 },
  { id: 'tale.cycle-year', title: '年轮', line: '茶客讲起四季轮回的年轮。「年轮是天的呼吸——体修的人，过好每一年，就是过好了一辈子。」', willpowerBonus: 40 },
  { id: 'tale.cycle-life', title: '生轮', line: '茶客讲起生是一轮的开始。「生是入场——体修的人，生得坦荡，这一轮才走得稳。」', willpowerBonus: 40 },
  { id: 'tale.cycle-death', title: '死轮', line: '茶客讲起死是一轮的收尾。「死不是终，是收——体修的人，死得其所，这一轮就圆满。」', willpowerBonus: 40 },
  { id: 'tale.cycle-rebirth', title: '重生', line: '茶客讲起每一春都是一次重生。「重生不在来世——体修的人，每一个春天，田都是重生。」', willpowerBonus: 50 },
  { id: 'tale.cycle-dao', title: '道轮', line: '茶客讲起道是最大的轮。「道轮无始无终——体修的人，在轮中找自己的位，就安了。」', willpowerBonus: 50 },
  { id: 'tale.cycle-still', title: '息轮', line: '茶客讲起轮停那一刻的永恒。「息轮是定——体修的人，偶尔让心停一停，就摸到了永恒。」', willpowerBonus: 40 },
  { id: 'tale.spring-awakening', title: '春醒', line: '茶客讲起春雷响后万物醒的生机。「春醒是天地重启——体修的人，春醒那刻，把心也跟着重启。」', willpowerBonus: 40 },
  { id: 'tale.summer-ripening', title: '夏熟', line: '茶客讲起盛夏万物疯长的盛。「夏熟是天地鼎盛——体修的人，夏熟时多流汗，秋才有收。」', willpowerBonus: 40 },
  { id: 'tale.autumn-gathering', title: '秋聚', line: '茶客讲起秋收把散的灵气聚拢。「秋聚是天地归藏前的聚——体修的人，秋聚时把田的收成聚进仓。」', willpowerBonus: 40 },
  { id: 'tale.winter-storing', title: '冬藏', line: '茶客讲起冬藏养蓄的智慧。「冬藏是天地歇息——体修的人，冬藏时把精气神都藏好，来春才旺。」', willpowerBonus: 40 },
  { id: 'tale.dawn-beginning', title: '晨启', line: '茶客讲起每日晨光是新的开始。「晨启是日之生——体修的人，每个晨启都当一辈子来过。」', willpowerBonus: 40 },
  { id: 'tale.dusk-ending', title: '暮归', line: '茶客讲起每日暮色是日的归。「暮归是日之收——体修的人，暮归时把一日收进心里，踏实睡去。」', willpowerBonus: 40 },
  { id: 'tale.full-bloom', title: '盛放', line: '茶客讲起灵草盛放那一刻的极美。「盛放是生命的顶——体修的人，盛放要看，也要懂它之后是收。」', willpowerBonus: 40 },
  { id: 'tale.quiet-rest', title: '安歇', line: '茶客讲起一切的终点是安歇。「安歇是体修的归——忙了一世，最后求的就是这两个字。」', willpowerBonus: 50 },
  { id: 'tale.artisan-pride', title: '匠傲', line: '茶客讲起匠人对作品的傲气。「傲不是狂——体修的人，对自己的活有一份傲，才精益求精。」', willpowerBonus: 40 },
  { id: 'tale.farmer-humility', title: '农谦', line: '茶客讲起农人面对天的谦卑。「谦是知天——体修的人，对天对地谦，才得天地之养。」', willpowerBonus: 40 },
  { id: 'tale.wanderer-freedom', title: '散修游', line: '茶客讲起散修走南闯北的自由。「游是开眼界——体修的人，偶学散修游一游，心就不窄。」', willpowerBonus: 40 },
  { id: 'tale.hermit-detachment', title: '隐士远', line: '茶客讲起隐士超然的远。「远不是避——体修的人，学隐士的远，是看透后的放下。」', willpowerBonus: 40 },
  { id: 'tale.guardian-duty', title: '守责', line: '茶客讲起守田人那份不卸的责。「责是担当——体修的人，守田守责，这份担当就是道。」', willpowerBonus: 40 },
  { id: 'tale.scholar-truth', title: '求真', line: '茶客讲起学者穷理求真的劲。「真是根——体修的人，学学者求真，把每个理都弄透。」', willpowerBonus: 40 },
  { id: 'tale.healer-compassion', title: '医仁', line: '茶客讲起医者父母心的仁。「仁是慈——体修的人，学医者的仁，连一株苗都怜惜。」', willpowerBonus: 40 },
  { id: 'tale.cook-nurture', title: '厨养', line: '茶客讲起厨子把粗粮变美味的养。「养是化——体修的人，学厨子的化，把凡日子过成滋养。」', willpowerBonus: 40 },
  { id: 'tale.balance-yin-yang', title: '阴阳衡', line: '茶客讲起阴阳平衡是体修的根。「阴不够补阴，阳不够补阳——体修的人，阴阳一衡，身子就安。」', willpowerBonus: 40 },
  { id: 'tale.balance-five-elements', title: '五行衡', line: '茶客讲起五行相生相克的巧。「五行要流转——体修的人，五行一衡，灵机就活。」', willpowerBonus: 40 },
  { id: 'tale.balance-hard-soft', title: '刚柔济', line: '茶客讲起刚柔并济的真意。「太刚易折，太柔无力——体修的人，刚柔济，才经久。」', willpowerBonus: 40 },
  { id: 'tale.balance-fast-slow', title: '疾徐', line: '茶客讲起疾徐有度的节奏。「疾在必要，徐在常日——体修的人，疾徐有度，不伤身。」', willpowerBonus: 40 },
  { id: 'tale.balance-give-take', title: '取予', line: '茶客讲起取予相当的道理。「只取不予，路越走越窄——体修的人，取予平衡，路才宽。」', willpowerBonus: 40 },
  { id: 'tale.balance-work-rest', title: '劳逸', line: '茶客讲起劳逸结合的智慧。「只劳不逸，人垮田荒——体修的人，劳逸有节，长久。」', willpowerBonus: 40 },
  { id: 'tale.balance-self-other', title: '人我', line: '茶客讲起人我之间的分寸。「太我不顾人，太人失我——体修的人，人我平衡，安处其中。」', willpowerBonus: 40 },
  { id: 'tale.balance-all', title: '万衡', line: '茶客讲起万物皆衡的大道。「衡是道的骨——体修的人，把衡活进日子，就是合道。」', willpowerBonus: 50 },
  { id: 'tale.moment-breathe', title: '一息', line: '茶客讲起忙乱中深吸一息的奇效。「一息能定神——体修的人，乱时先一息，再动手。」', willpowerBonus: 40 },
  { id: 'tale.moment-glance', title: '一瞥', line: '茶客讲起偶然一瞥救了田的事。「一瞥看见苗蔫了——体修的人，眼要勤，一瞥能避大灾。」', willpowerBonus: 40 },
  { id: 'tale.moment-step', title: '一步', line: '茶客讲起每一步都走稳的道理。「一步稳，步步稳——体修的人，不贪步，一步一个印。」', willpowerBonus: 40 },
  { id: 'tale.moment-word', title: '一言', line: '茶客讲起一句承诺重千斤。「一言既出——体修的人，话不轻许，许了就一定办到。」', willpowerBonus: 40 },
  { id: 'tale.moment-thought', title: '一念', line: '茶客讲起一念之差能定成败。「一念要正——体修的人，念头一起，就往正路上引。」', willpowerBonus: 40 },
  { id: 'tale.moment-smile', title: '一笑', line: '茶客讲起对苦难一笑置之的豁达。「一笑能解千愁——体修的人，难时一笑，比硬扛还顶用。」', willpowerBonus: 40 },
  { id: 'tale.moment-tear', title: '一泪', line: '茶客讲起偶尔落一泪不是弱。「一泪是泄——体修的人，泪不憋，泄完更硬朗。」', willpowerBonus: 40 },
  { id: 'tale.moment-sigh', title: '一叹', line: '茶客讲起长叹一声后的轻松。「一叹放下了半担——体修的人，叹一声无妨，叹完继续走。」', willpowerBonus: 40 },
  { id: 'tale.image-mountain', title: '山', line: '茶客讲起山教会人的稳。「山不动——体修的人，学山的稳，任风雷不动。」', willpowerBonus: 40 },
  { id: 'tale.image-water', title: '水', line: '茶客讲起水教会人的柔韧。「水不争——体修的人，学水的柔，绕得过一切硬。」', willpowerBonus: 40 },
  { id: 'tale.image-tree', title: '树', line: '茶客讲起树教会人的扎根。「树往上长先往下扎——体修的人，学树的扎根，根深才枝繁。」', willpowerBonus: 40 },
  { id: 'tale.image-stone', title: '石', line: '茶客讲起石教会人的耐。「石不动声色——体修的人，学石的耐，经得起风雨。」', willpowerBonus: 40 },
  { id: 'tale.image-cloud', title: '云', line: '茶客讲起云教会人的散淡。「云无定形——体修的人，学云的散淡，不执著形相。」', willpowerBonus: 40 },
  { id: 'tale.image-moon-tale', title: '月', line: '茶客讲起月教会人的盈亏。「月有圆缺——体修的人，学月的盈亏，懂了不强常圆。」', willpowerBonus: 40 },
  { id: 'tale.image-sun-tale', title: '日', line: '茶客讲起日教会人的无私。「日普照不偏——体修的人，学日的无私，光照万物。」', willpowerBonus: 40 },
  { id: 'tale.image-star-tale', title: '星', line: '茶客讲起星教会人的守位。「星各守其位——体修的人，学星的守，找到自己的位就安。」', willpowerBonus: 40 },
  { id: 'tale.texture-rough', title: '粗', line: '茶客讲起粗糙手感里的踏实。「粗是实在——体修的人，粗茶粗饭粗布，养出的是真功夫。」', willpowerBonus: 40 },
  { id: 'tale.texture-smooth', title: '滑', line: '茶客讲起光滑表面下的隐患。「滑易失手——体修的人，对太滑的东西多一分小心。」', willpowerBonus: 40 },
  { id: 'tale.texture-warm', title: '温', line: '茶客讲起温润待人接物的好处。「温是养人——体修的人，对人温，对己温，路走得暖。」', willpowerBonus: 40 },
  { id: 'tale.texture-cool', title: '凉', line: '茶客讲起凉性灵草清火的妙。「凉是清——体修的人，燥时一点凉，就压回了平。」', willpowerBonus: 40 },
  { id: 'tale.texture-heavy', title: '沉', line: '茶客讲起沉甸甸收成的那份满足。「沉是实——体修的人，沉甸甸的，心里最踏实。」', willpowerBonus: 40 },
  { id: 'tale.texture-light', title: '轻', line: '茶客讲起轻装上阵的自在。「轻是省——体修的人，身上轻，心里就轻。」', willpowerBonus: 40 },
  { id: 'tale.texture-dense', title: '密', line: '茶客讲起灵草种密了反而不好的道理。「密不透风——体修的人，留疏，苗才长得开。」', willpowerBonus: 40 },
  { id: 'tale.texture-sparse', title: '疏', line: '茶客讲起留疏的智慧。「疏是透——体修的人，日子也该留疏，透得过气。」', willpowerBonus: 40 },
  { id: 'tale.journey-first-step', title: '千里始', line: '茶客讲起千里之行始于足下。「千里不远——体修的人，迈出第一步，千里就开始了。」', willpowerBonus: 40 },
  { id: 'tale.journey-halfway', title: '半途', line: '茶客讲起半途最易松懈。「半途最险——体修的人，过半不松，一鼓作气。」', willpowerBonus: 40 },
  { id: 'tale.journey-near-end', title: '近终', line: '茶客讲起近终点反而更慢的智慧。「近终要稳——体修的人，越近终点越要沉，别功亏一篑。」', willpowerBonus: 40 },
  { id: 'tale.journey-return-home', title: '归途', line: '茶客讲起归途比去程还暖。「归途心定——体修的人，走得再远，归途那刻最暖。」', willpowerBonus: 40 },
  { id: 'tale.journey-detour', title: '绕路', line: '茶客讲起绕路看见的别样风景。「绕路不亏——体修的人，偶尔绕一绕，看见的不是终点是路。」', willpowerBonus: 40 },
  { id: 'tale.journey-stray', title: '迷途', line: '茶客讲起迷途后找回路的那份庆幸。「迷了不怕——体修的人，迷了能找回，路就还在。」', willpowerBonus: 40 },
  { id: 'tale.journey-rest-stop', title: '歇脚', line: '茶客讲起赶路途中歇一脚的必要。「歇脚是续——体修的人，会赶路也要会歇脚。」', willpowerBonus: 40 },
  { id: 'tale.journey-companion', title: '同行', line: '茶客讲起路上遇到同行者的暖。「同行不孤——体修的人，路长，有个同行，是福。」', willpowerBonus: 50 },
  { id: 'tale.gather-herb', title: '采草', line: '茶客讲起清晨进田采灵草的讲究。「带露采的灵草药性最足——体修的人，采草看时辰。」', willpowerBonus: 40 },
  { id: 'tale.gather-mushroom', title: '采菇', line: '茶客讲起雨后林里采朝阳菇的乐趣。「雨后菇最肥——体修的人，采菇也是一份天赐的收。」', willpowerBonus: 40 },
  { id: 'tale.gather-fruit', title: '采果', line: '茶客讲起秋日采灵果的丰收喜悦。「果熟自落——体修的人，采果是收成的高潮。」', willpowerBonus: 40 },
  { id: 'tale.gather-water', title: '汲水', line: '茶客讲起清晨第一桶井水的清甜。「第一桶最灵——体修的人，汲水也挑时辰。」', willpowerBonus: 40 },
  { id: 'tale.gather-wood', title: '拾柴', line: '茶客讲起秋后拾柴备冬的踏实。「柴备足了冬不慌——体修的人，拾柴是过冬的底气。」', willpowerBonus: 40 },
  { id: 'tale.gather-stone', title: '拾石', line: '茶客讲起翻地拾出的碎石另有用。「碎石垫阵脚——体修的人，拾出的石不弃，另有用处。」', willpowerBonus: 40 },
  { id: 'tale.gather-honey', title: '采蜜', line: '茶客讲起取灵蜂蜜那份小心翼翼。「蜜是蜂的心血——体修的人，取蜜留一半，蜂才不弃你。」', willpowerBonus: 40 },
  { id: 'tale.gather-salt', title: '取盐', line: '茶客讲起远方运来的盐的珍贵。「盐是百味之首——体修的人，盐虽凡物，却养得出百味日子。」', willpowerBonus: 40 },
  { id: 'tale.age-childhood', title: '童时', line: '茶客讲起童年跟父辈学种田的无忧。「童时最纯——体修的人，记得童时那份纯，种田就种得真。」', willpowerBonus: 40 },
  { id: 'tale.age-youth', title: '少时', line: '茶客讲起少年时一身干劲的莽。「少时最冲——体修的人，少时的冲要护住，那是凡骨的火。」', willpowerBonus: 40 },
  { id: 'tale.age-prime', title: '壮时', line: '茶客讲起壮年独当一面的稳。「壮时最稳——体修的人，壮年撑起一片田，是这条路的中坚。」', willpowerBonus: 40 },
  { id: 'tale.age-middle', title: '中年', line: '茶客讲起中年懂得取舍的通透。「中年最通——体修的人，中年懂了舍，留下的才是真的。」', willpowerBonus: 40 },
  { id: 'tale.age-elder', title: '老时', line: '茶客讲起老来慢下来的自在。「老时最慢——体修的人，老来慢，反而看得最清。」', willpowerBonus: 40 },
  { id: 'tale.age-sunset', title: '暮年', line: '茶客讲起暮年回望一生的释然。「暮年最释——体修的人，暮年回望，该做的都做了，就释然。」', willpowerBonus: 50 },
  { id: 'tale.age-end', title: '临终', line: '茶客讲起临终前交代后事的那份静。「临终最静——体修的人，临终那份静，是一辈子修来的。」', willpowerBonus: 50 },
  { id: 'tale.age-legacy', title: '身后', line: '茶客讲起身后人记得你的才是真留。「身后不虚——体修的人，留世的人，身后留的是田和故事。」', willpowerBonus: 40 },
  { id: 'tale.weather-fog', title: '晨雾', line: '茶客讲起晨雾弥漫时田的朦胧美。「雾是天的纱——体修的人，雾天翻地，潮气养根。」', willpowerBonus: 40 },
  { id: 'tale.weather-dew', title: '朝露', line: '茶客讲起朝露润灵草的那份柔。「露是天的奶——体修的人，朝露最养苗。」', willpowerBonus: 40 },
  { id: 'tale.weather-frost-tale', title: '霜', line: '茶客讲起秋霜早降的警觉。「霜是秋的鞭——体修的人，见霜就知该抢收了。」', willpowerBonus: 40 },
  { id: 'tale.weather-hail', title: '雹', line: '茶客讲起夏雹砸坏棚的惊心。「雹是天的怒——体修的人，雹后补棚，是必修的课。」', willpowerBonus: 40 },
  { id: 'tale.weather-sleet', title: '霰', line: '茶客讲起雨雪交加的难熬。「霰最阴冷——体修的人，霰天不出田，守棚为上。」', willpowerBonus: 40 },
  { id: 'tale.weather-mist', title: '霭', line: '茶客讲起山霭聚散的悠然。「霭是山的呼吸——体修的人，看霭，心也跟着悠。」', willpowerBonus: 40 },
  { id: 'tale.weather-haze-tale', title: '霾', line: '茶客讲起霾天闷人的压抑。「霾是气滞——体修的人，霾天不出田，静守过。」', willpowerBonus: 40 },
  { id: 'tale.weather-clear', title: '晴', line: '茶客讲起雨后初晴的那份敞亮。「晴是天的笑——体修的人，晴日翻地晒种，最是利落。」', willpowerBonus: 40 },
  { id: 'tale.body-bone', title: '骨', line: '茶客讲起骨是体修的梁。「骨正体才正——体修的人，养骨是养一身正气。」', willpowerBonus: 40 },
  { id: 'tale.body-marrow', title: '髓', line: '茶客讲起髓是骨的精。「髓足骨才坚——体修的人，洗髓是洗出骨里的精。」', willpowerBonus: 40 },
  { id: 'tale.body-blood', title: '血', line: '茶客讲起血是身的河。「血畅身才轻——体修的人，凝血是让这条河沉而有力。」', willpowerBonus: 40 },
  { id: 'tale.body-muscle', title: '筋', line: '茶客讲起筋是骨的索。「筋柔体才灵——体修的人，拉筋是让身听话。」', willpowerBonus: 40 },
  { id: 'tale.body-skin', title: '皮', line: '茶客讲起皮是身的屏。「皮厚御外邪——体修的人，养皮是养第一道关。」', willpowerBonus: 40 },
  { id: 'tale.body-heart-tale', title: '心', line: '茶客讲起心是身的主。「心定万事定——体修的人，养心是养一身之主。」', willpowerBonus: 50 },
  { id: 'tale.body-spirit', title: '神', line: '茶客讲起神是心的光。「神清人清明——体修的人，养神是养人的清明。」', willpowerBonus: 40 },
  { id: 'tale.body-breath-qi', title: '气', line: '茶客讲起气是身的帆。「气足行万里——体修的人，养气是养一身的帆。」', willpowerBonus: 40 },
  { id: 'tale.trade-merchant', title: '商', line: '茶客讲起商是流通的血脉。「商通万物——体修的人，不轻商，商让山谷的灵物流动起来。」', willpowerBonus: 40 },
  { id: 'tale.trade-barter', title: '易', line: '茶客讲起以物易物最见信任。「易是信——体修的人，易物不唯利，凭的是信。」', willpowerBonus: 40 },
  { id: 'tale.trade-credit', title: '赊', line: '茶客讲起赊账是情分也是规矩。「赊要还——体修的人，赊是情，还是规矩，两清才长久。」', willpowerBonus: 40 },
  { id: 'tale.trade-trust', title: '信', line: '茶客讲起信是商的根。「无信不立——体修的人，做生意先立信，信立则路通。」', willpowerBonus: 40 },
  { id: 'tale.trade-quality', title: '质', line: '茶客讲起货真价实才长久。「质是本——体修的人，不卖假货，质硬名声才硬。」', willpowerBonus: 40 },
  { id: 'tale.trade-honesty-tale', title: '诚', line: '茶客讲起对客的诚。「诚能换心——体修的人，待客以诚，客才回头。」', willpowerBonus: 40 },
  { id: 'tale.trade-patience', title: '等', line: '茶客讲起好价要等的耐性。「急卖贱卖——体修的人，等得起，价才上得去。」', willpowerBonus: 40 },
  { id: 'tale.trade-reputation', title: '名', line: '茶客讲起名声比灵石重。「名是金——体修的人，护名声比护灵石更上心。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-rat', title: '鼠', line: '茶客讲起鼠虽小却机灵。「鼠教人机警——体修的人，学鼠的机灵，能避暗祸。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-ox', title: '牛', line: '茶客讲起牛的踏实勤恳。「牛教人勤——体修的人，学牛的踏实，一步一印。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-tiger', title: '虎', line: '茶客讲起虎的威严果决。「虎教人勇——体修的人，学虎的果决，关键时刻不退缩。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-rabbit', title: '兔', line: '茶客讲起兔的敏捷谨慎。「兔教人敏——体修的人，学兔的敏，险境脱身。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-dragon', title: '龙', line: '茶客讲起龙的腾飞之志。「龙教人志——体修的人，学龙的志，却不贪飞升，志在脚下。」', willpowerBonus: 50 },
  { id: 'tale.zodiac-snake', title: '蛇', line: '茶客讲起蛇的柔韧伺机。「蛇教人忍——体修的人，学蛇的忍，伺机而动。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-horse', title: '马', line: '茶客讲起马的奔放耐力。「马教人行——体修的人，学马的耐力，路远行得稳。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-goat', title: '羊', line: '茶客讲起羊的温顺群居。「羊教人和——体修的人，学羊的和，与山谷邻里和睦。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-monkey', title: '猴', line: '茶客讲起猴的灵巧变通。「猴教人巧——体修的人，学猴的巧，遇山开路。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-rooster', title: '鸡', line: '茶客讲起鸡的守信报晓。「鸡教人信——体修的人，学鸡的信，每日不爽约。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-dog', title: '狗', line: '茶客讲起狗的忠诚看护。「狗教人忠——体修的人，学狗的忠，守田不二。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-pig', title: '猪', line: '茶客讲起猪的知足囤养。「猪教人足——体修的人，学猪的知足，攒得住福。」', willpowerBonus: 40 },
  { id: 'tale.zodiac-cat-tale', title: '猫', line: '茶客讲起猫的独立从容。「猫教人独——体修的人，学猫的从容，独处不慌。」', willpowerBonus: 40 },
  { id: 'tale.forest-deep', title: '深林', line: '茶客讲起深林里的幽秘。「深林藏奇——体修的人，偶入深林，能遇稀世灵草。」', willpowerBonus: 40 },
  { id: 'tale.river-source', title: '源头', line: '茶客讲起追寻溪水源头的那次远足。「寻源见清——体修的人，寻到源头，才知这一脉水的来路。」', willpowerBonus: 40 },
  { id: 'tale.mountain-peak-tale', title: '山顶', line: '茶客讲起登顶看整片山谷的豁达。「登顶心阔——体修的人，偶登山顶，看见自己守的这片有多大。」', willpowerBonus: 50 },
  { id: 'tale.virtue-filial', title: '孝', line: '茶客讲起孝是百善之首。「孝是根——体修的人，连父母都不孝，谈何修仙。」', willpowerBonus: 40 },
  { id: 'tale.virtue-fraternal', title: '悌', line: '茶客讲起悌是兄弟和睦。「悌是和——体修的人，兄弟和睦，家才齐。」', willpowerBonus: 40 },
  { id: 'tale.virtue-loyalty-v', title: '忠', line: '茶客讲起忠是尽心。「忠是诚——体修的人，对人对事尽心，就是忠。」', willpowerBonus: 40 },
  { id: 'tale.virtue-propriety', title: '礼', line: '茶客讲起礼是节度。「礼是度——体修的人，礼多人不怪，是分寸。」', willpowerBonus: 40 },
  { id: 'tale.virtue-righteousness', title: '义', line: '茶客讲起义是该为。「义是当——体修的人，该为则为，不当为则止。」', willpowerBonus: 40 },
  { id: 'tale.virtue-integrity', title: '廉', line: '茶客讲起廉是不贪。「廉是清——体修的人，不贪不占，一身清。」', willpowerBonus: 40 },
  { id: 'tale.virtue-shame', title: '耻', line: '茶客讲起知耻是修身的始。「耻是警——体修的人，知耻而后改，是修身的起点。」', willpowerBonus: 40 },
  { id: 'tale.virtue-forgiveness', title: '恕', line: '茶客讲起恕是宽人宽己。「恕是宽——体修的人，恕人恕己，心就不窄。」', willpowerBonus: 40 },
  { id: 'tale.plant-root-tale', title: '根', line: '茶客讲起根是灵草的命。「根深命才长——体修的人，养草先养根。」', willpowerBonus: 40 },
  { id: 'tale.plant-stem', title: '茎', line: '茶客讲起茎是灵草的梁。「茎壮撑得起——体修的人，看茎就知道草壮不壮。」', willpowerBonus: 40 },
  { id: 'tale.plant-leaf-tale', title: '叶', line: '茶客讲起叶是灵草的肺。「叶茂呼吸旺——体修的人，叶茂的草灵机足。」', willpowerBonus: 40 },
  { id: 'tale.plant-flower', title: '花', line: '茶客讲起花是灵草的笑。「花开是草在笑——体修的人，看见花，就知道养对了。」', willpowerBonus: 40 },
  { id: 'tale.plant-fruit-tale', title: '果', line: '茶客讲起果是灵草的赠。「果是草给的回礼——体修的人，收果是收草的谢。」', willpowerBonus: 40 },
  { id: 'tale.plant-seed-tale', title: '种', line: '茶客讲起种是灵草的来年。「种好来年旺——体修的人，留种是留来年的根。」', willpowerBonus: 40 },
  { id: 'tale.plant-sprout', title: '芽', line: '茶客讲起芽是灵草的新生。「芽是新——体修的人，看见芽，就看见新希望。」', willpowerBonus: 40 },
  { id: 'tale.plant-wither', title: '枯', line: '茶客讲起枯是灵草的归。「枯不是废——体修的人，枯草归土，养下一茬。」', willpowerBonus: 40 },
  { id: 'tale.grain-rice', title: '稻', line: '茶客讲起稻是凡间的主粮。「稻养天下——体修的人，凡田也种稻，养的是底。」', willpowerBonus: 40 },
  { id: 'tale.grain-millet', title: '粟', line: '茶客讲起粟耐旱好养活。「粟最皮实——体修的人，荒年有粟就不慌。」', willpowerBonus: 40 },
  { id: 'tale.grain-wheat', title: '麦', line: '茶客讲起麦是北方的主食。「麦养筋骨——体修的人，凡田也种麦，养的是力。」', willpowerBonus: 40 },
  { id: 'tale.grain-bean', title: '菽', line: '茶客讲起豆能肥田又能养人。「豆是双养——体修的人，凡田轮作种豆，养地养人。」', willpowerBonus: 40 },
  { id: 'tale.grain-sorghum', title: '粱', line: '茶客讲起粱是精粮。「粱养神——体修的人，偶尔吃顿粱饭，是犒劳自己。」', willpowerBonus: 40 },
  { id: 'tale.vegetable-melon', title: '瓜', line: '茶客讲起瓜是夏日的甜。「瓜解暑——体修的人，夏田有瓜，日子就甜。」', willpowerBonus: 40 },
  { id: 'tale.vegetable-leaf-veg', title: '菜', line: '茶客讲起青菜是日常的清淡。「菜养清——体修的人，顿顿有菜，身子不腻。」', willpowerBonus: 40 },
  { id: 'tale.fruit-orchard', title: '园', line: '茶客讲起自家小果园的乐趣。「园不在大——体修的人，几株果树，年年有收就是福。」', willpowerBonus: 40 },
  { id: 'tale.furnish-bed', title: '床', line: '茶客讲起累了一天躺上床的踏实。「床是歇的窝——体修的人，一张好床，比什么丹都养人。」', willpowerBonus: 40 },
  { id: 'tale.furnish-table', title: '桌', line: '茶客讲起那张用了半辈子的旧饭桌。「桌是聚的处——体修的人，一家围桌吃饭，是最暖的景。」', willpowerBonus: 40 },
  { id: 'tale.furnish-chair', title: '椅', line: '茶客讲起那把摇得吱呀响的旧椅。「椅是歇的伴——体修的人，摇椅上一坐，半日烦忧都摇散了。」', willpowerBonus: 40 },
  { id: 'tale.furnish-lamp-stand', title: '灯架', line: '茶客讲起守夜那盏灯架的稳。「灯架稳，灯火才不晃——体修的人，灯架是守夜的骨。」', willpowerBonus: 40 },
  { id: 'tale.furnish-bookshelf', title: '书架', line: '茶客讲起那架记田事的书。「书架是脑——体修的人，记下的田事，是来年的谱。」', willpowerBonus: 40 },
  { id: 'tale.furnish-kitchen-stove', title: '灶', line: '茶客讲起灶火是一家暖的源。「灶旺家暖——体修的人，灶火不熄，日子就有人气。」', willpowerBonus: 40 },
  { id: 'tale.furnish-window', title: '窗', line: '茶客讲起那扇看田的窗。「窗是家的眼——体修的人，开窗见田，心就安。」', willpowerBonus: 40 },
  { id: 'tale.furnish-door', title: '门', line: '茶客讲起那扇迎过多少客的门。「门是家的口——体修的人，门常开迎客，也常闭守己。」', willpowerBonus: 40 }
];

/** 今日是否为茶客奇闻日：按当季第几日确定性判定，无新持久字段。 */
export function isTeaShedTaleDay(state: GameState): boolean {
  return state.seasonDay > 0 && state.seasonDay % 5 === 0;
}

/** 奇闻日返回当日茶客奇闻（按日确定性轮换），否则返回 null。 */
export function getTeaShedTale(state: GameState): TeaShedTale | null {
  if (!isTeaShedTaleDay(state)) return null;
  const index = Math.floor(Math.max(1, state.day) / 5) % TEA_SHED_TALES.length;
  return TEA_SHED_TALES[index]!;
}

const TEA_SHED_RUMORS: readonly TeaShedRumor[] = [
  {
    id: 'quiet-harvest',
    title: '茶火慢熬',
    lines: ['棚里老火煨着药茶。', '散修说留世之后，守得住一季收成，也是与天争回来的日子。']
  },
  {
    id: 'ward-boundary',
    title: '守境余谈',
    lines: ['来客提起村镇外新补的护田阵。', '你若肯留下，拳脚不必离地，也能替人间挡住一截风雨。']
  },
  {
    id: 'vein-weather',
    title: '残脉风向',
    lines: ['茶棚窗边挂着残脉风铃。', '驳杂灵气最怕硬顶，先借阵势，再近身破局，体修才能走得更长。']
  },
  {
    id: 'mortal-dawn',
    title: '凡人灯火',
    lines: ['夜里村灯连成细线。', '飞不飞升是一回事，能不能让凡人的灯火稳稳亮着，是另一回事。']
  },
  {
    id: 'array-maintenance',
    title: '护阵余话',
    lines: ['茶客说起自家护田阵总在雷季后松一处。', '阵这东西，补得勤比布得大更顶用——和种田一个理。']
  },
  {
    id: 'off-season-tea',
    title: '反季灵茶',
    lines: ['棚里烘着反季才有的半两茶尖。', '留世的人不赶时令，反倒能把时令里最细的那一茬留下来。']
  },
  {
    id: 'mortal-craft',
    title: '凡人手艺',
    lines: ['棚外有凡匠在修整晒架。', '你说不清是修仙修到了这份从容，还是种田种回了这份手艺。']
  }
];

export function teaShedVisitFlag(day: number): string {
  return `tea-shed-visit.${day}`;
}

/**
 * 连续前序留世日已在旧茶棚歇脚的天数（不含今日；扫描上限 7 日，够判定常客两档奖励）。
 * 由 flags 派生，不引入新持久字段（旧档自动兼容）。design spec P2 茶棚/闲居支线。
 */
export function teaShedVisitStreak(state: GameState): number {
  let prior = 0;
  for (let day = state.day - 1; day >= 1 && prior < 7; day -= 1) {
    if (state.flags.has(teaShedVisitFlag(day))) prior += 1;
    else break;
  }
  return prior;
}

/** 旧茶棚常客成就：首次达到 3 日连击后永久记录（一次性目标锚点）。 */
export const TEA_REGULAR_ACHIEVEMENT_FLAG = 'tea-shed-regular-achieved';

export function hasTeaShedRegularAchievement(state: GameState): boolean {
  return state.flags.has(TEA_REGULAR_ACHIEVEMENT_FLAG);
}

export function getTeaShedRumor(state: GameState): TeaShedRumor {
  const index = (state.day + state.seasonDay + state.player.stage) % TEA_SHED_RUMORS.length;
  return TEA_SHED_RUMORS[index]!;
}

export function visitTeaShed(state: GameState, ctx: SimContext): VisitTeaShedResult {
  const rumor = getTeaShedRumor(state);
  const season = state.season;
  if (state.postAscension.mode !== 'stayed-in-world') {
    return { ok: false, reason: '唯有留世后方能在旧茶棚安坐听闻', rumor, season, hpGain: 0, poisonRelief: 0, willpowerGain: 0, staminaCost: 0, streak: 0, streakBonus: 0, tale: null };
  }

  const visitFlag = teaShedVisitFlag(state.day);
  if (state.flags.has(visitFlag)) {
    return { ok: false, reason: '今日已在旧茶棚歇过脚', rumor, season, hpGain: 0, poisonRelief: 0, willpowerGain: 0, staminaCost: 0, streak: 0, streakBonus: 0, tale: null };
  }

  // 季节性体力消耗：身体的安坐节律随四时相应。
  const staminaCost = TEA_SHED_STAMINA_COST_BY_SEASON[season] * MILLI;
  if (state.player.stamina < staminaCost) {
    return { ok: false, reason: '体力不足', rumor, season, hpGain: 0, poisonRelief: 0, willpowerGain: 0, staminaCost, streak: 0, streakBonus: 0, tale: null };
  }

  // 常客连击：连续歇脚放大意志与排毒，资深常客（≥7 日）再升一档。
  const streak = teaShedVisitStreak(state) + 1; // 今日计入
  const masterRegular = streak >= 7;
  const regular = streak >= 3;
  const streakBonus = masterRegular ? 2 : regular ? 1 : 0;

  // 季节性清闲收益：春为基准（零加成，保持既有节奏），夏清暑排毒、秋凝志、冬养藏深息。
  const seasonalHp = TEA_SHED_SEASONAL_HP_MILLI[season] * MILLI;
  const seasonalPoisonCap = TEA_SHED_SEASONAL_POISON_CAP[season];
  const seasonalWillpower = TEA_SHED_SEASONAL_WILLPOWER[season];

  // 歇脚事件分支：奇闻日偶遇茶客留下点拨，额外增益意志。
  // 常客在奇闻日与茶客共鸣，奇闻意志收益翻倍。
  const tale = getTeaShedTale(state);
  const baseTaleWillpower = tale?.willpowerBonus ?? 0;
  const regularTaleResonance = regular && tale != null;
  const taleWillpower = regularTaleResonance ? baseTaleWillpower * 2 : baseTaleWillpower;

  state.player.stamina -= staminaCost;
  const hpGain = 8 * MILLI + seasonalHp;
  const poisonReliefCap = (ctx.params.pillPoison.restBonusMax + streakBonus + seasonalPoisonCap) * MILLI;
  const poisonRelief = Math.min(state.player.pillPoison, poisonReliefCap);
  const willpowerGain = 180 + (masterRegular ? 240 : regular ? 120 : 0) + seasonalWillpower + taleWillpower;
  state.player.hp = Math.min(state.player.maxHp, state.player.hp + hpGain);
  state.player.pillPoison = Math.max(0, state.player.pillPoison - poisonRelief);
  state.player.willpower += willpowerGain;
  state.flags.add(visitFlag);
  if (streak >= 3) state.flags.add(TEA_REGULAR_ACHIEVEMENT_FLAG);
  emit(state, 'tea-shed-visit', {
    rumorId: rumor.id,
    season,
    hpGain,
    poisonRelief,
    willpowerGain,
    staminaCost,
    streak,
    streakBonus,
    seasonalHpGain: seasonalHp,
    seasonalPoisonCapBonus: seasonalPoisonCap,
    seasonalWillpowerGain: seasonalWillpower,
    taleId: tale?.id ?? null,
    taleWillpowerGain: taleWillpower,
    regularTaleResonance
  });

  return { ok: true, rumor, season, hpGain, poisonRelief, willpowerGain, staminaCost, streak, streakBonus, tale };
}
